### ISSUE TITLE
Projects/FilterBar: clean up Sorting

### ISSUE THREAD

**Issue by chadoh** [AutarkLabs/open-enterprise#1005]
Follow up to #966 

Clean up the Sorting logic and behavior for `FilterBar` in Projects. Here's what it looks like now:

<img width="177" alt="Screen Shot 2019-06-19 at 11 23 05" src="https://user-images.githubusercontent.com/221614/59778511-a39fad80-9284-11e9-86e7-a1da45cdde00.png">

What we want to do:

- [ ] Rework interaction between `sortBy` [in `Issues`](https://github.com/AutarkLabs/planning-suite/blob/56b745d16ade07904b27ceb1aeffaa00a145550e/apps/projects/app/components/Content/Issues.js#L59) vs [in `FilterBar`](https://github.com/AutarkLabs/planning-suite/blob/56b745d16ade07904b27ceb1aeffaa00a145550e/apps/projects/app/components/Shared/FilterBar/FilterBar.js#L20-L26) – currently, rather than one component driving the other, both share some logic about the structure of sorting objects, and both contain (conflicting?) logic about the default sort order

- [ ] Rather than only "Sort by creation date" with never-obvious logic around "ascending" vs "descending" ("up arrow" vs "down arrow"), let's copy GitHub's approach to sorting:

   ![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/b2f40b39-0d1f-4e05-af55-5f0a3f6c68e3)

**Comment by jayalaves** [comment]
Just to substitute what we have, it would look like...
- Name ascending (A-Z)
- Name descending (Z-A)
- Newest
- Oldest

Once contextual discussions are implemented, we could also do...
- Most commented
- Least commented

**Comment by stellarmagnet** [comment]
Closing: this should be covered in #1113
