### ISSUE TITLE
Use new forwarder API to pass information from discussions app to address book

### ISSUE THREAD

**Issue by Schwartz10** [AutarkLabs/open-enterprise#1049]

**Comment by ottodevs** [comment]
This issue has a bounty attached to it.
Amount: 1.00 autark
Deadline: Wed, 10 Jul 2019 14:55:26 GMT

**Comment by ottodevs** [comment]
This issue has a bounty attached to it.
Amount: 2.00 autark
Deadline: Wed, 10 Jul 2019 15:12:46 GMT

**Comment by ottodevs** [comment]
This issue has a bounty attached to it.
Amount: 2.00 autark
Deadline: Wed, 10 Jul 2019 15:15:24 GMT
