### ISSUE TITLE
Background color of application region in Review Applicant panel should be the same as the Review Work panel

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1055]
Let's go with the blue used in Review Applicant

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/4416e72c-a74e-4bdc-9c5f-1705f6eff935)

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/a29d9593-8e90-4dc0-828a-b871d2fd19a6)

**Comment by chadoh** [comment]
This is covered by #1113
