### ISSUE TITLE
Research Potential Contract level changes to integrate Projects/Voting app with deep linking

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#1062]
Once we have the ability to pass deep links from Projects into voting we need to check the Radspec for our functions and see if any of the contract functions need to be changed to respond to the existence of deep linking.

**Comment by stellarmagnet** [comment]
@ottodevs please document your research in a Notion document and provide the link before moving this into "review".

**Comment by ottodevs** [comment]
We need deeplinking implemented before being able to have actual progress on this task...
Anyway, apparently the only changes needed are related to radspec.

Deep-linking is something related to the frontend, the correct terminology should by routing path or custom routing paths, we probably would like to have the portion of the path with the link in some `radspec` messages, like for specific votes, profiles, or more generally **app sections**

Radspec is not able to do so much in this field apart from showing a string with that custom path, and the contract has nothing to do with that...

Eventually the Aragon client could be modified to convert those path string into actual clickable links, but this is something really not important, most pages have links and 100% of internet users know how to click a non-clickable link, even most browsers have the option to navigate to non-clickable links, so it is just a cosmetic change.

A different scenario could happen with desktop or mobile versions of Aragon client, where those links should be converted to WebView routes, or whatever, but for that to happen, we would need first to support Desktop/mobile, and the custom path implementation should be consistently finished, additional research on this task will probably head to the same conclusions.

**Comment by stellarmagnet** [comment]
Closing this, it should be covered in #1157
