### ISSUE TITLE
Address Book: improve error handling / validation

### ISSUE THREAD

**Issue by chadoh** [AutarkLabs/open-enterprise#1093]
We already validate that ethereum addresses are well-formed.

We also seem to have validation to prevent users from adding the same contact twice, but there's no user-facing message shown.

Let's fix that.

**Comment by Quazia** [comment]
This issue has a bounty attached to it.
Amount: 1.00 autark
Deadline: Thu, 18 Jul 2019 04:17:30 GMT

**Comment by Quazia** [comment]
This issue has a bounty attached to it.
Amount: 1.00 autark
Deadline: Thu, 18 Jul 2019 05:17:28 GMT

**Comment by ottodevs** [comment]
This issue has a bounty attached to it.
Amount: 2.00 autark
Deadline: Thu, 18 Jul 2019 22:50:08 GMT

**Comment by chadoh** [comment]
Duplicate of #1173
