### ISSUE TITLE
Test dot-voting with balances of more than 1999

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#1097]
It's possible dot-voting does not work when a voter holds a balance of more than 1999 tokens.

**Comment by stellarmagnet** [comment]
Look into if math-utils can help clean up our big number issues

**Comment by topocount** [comment]
After some investigation with BN.js and how numbers are passed into the `web3.utils.toBN` function. If we pass around raw strings like `'2000000000000000000000'` and never let them become `Number`s I'm confident we'll resolve this issue and avoid this bug in the future. A1's `math-utils` will be excellent in helpings us to stay DRY and keep good pracitices
