### ISSUE TITLE
Document the technical spec for quasi-transferable tokens

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1132]
There have been many discussions in progress about quasi-transferable tokens and the technical solution, yet nothing has been documented (as far as I can tell).

We need to ensure the solution is documented so everyone understands the approach.

(Issue #977 was marked as completed, yet no solution was provided).

Document this here: https://www.notion.so/autark/Quasi-transferable-token-solution-778c6ffdbc5149d1916f86a971f746fa

**Comment by stellarmagnet** [comment]
This is a blocker for design work and needs to be prioritized.

**Comment by Quazia** [comment]
This has been handed over to Brett & Jorge for review, will update the notion with feedback but it should be safe to start design work on.
https://www.notion.so/autark/Quasi-transferable-token-solution-778c6ffdbc5149d1916f86a971f746fa
