### ISSUE TITLE
Provide ability to enter a bounty amount without using the hours calculator

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1158]

**Comment by stellarmagnet** [comment]
@jayalaves do we have the design for this?

**Comment by jayalaves** [comment]
@stellarmagnet It's part of my design specs for the upcoming iteration on Projects -- I'll update as soon as we do (just a matter of a day or two)

**Comment by jayalaves** [comment]
I've introduced this feature [in our Figma file](https://www.figma.com/file/Xnn4lQJX4d5AautuvmAlnxHf/Projects?node-id=223%3A2072).
