### ISSUE TITLE
Do not allow reward to be submitted if date range is invalid

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1162]
![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/879df7ba-d845-4a09-a3cd-56ac500f45f2)

**Comment by lcoenen** [comment]
Right now, there is no warning when the starting date is posterior to the ending date. 
<img width="532" alt="image" src="https://user-images.githubusercontent.com/1237971/65686210-c4358b80-e05b-11e9-8896-dcde5a488b93.png">

**Comment by lcoenen** [comment]
I cannot reproduce this:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/1237971/65767641-55713480-e126-11e9-9e63-ece125e68c3e.png">
