### ISSUE TITLE
Participation is 99.99% even though voting with 100 dots

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1193]
In a DAO with a single token holder and voting with 100 dots, participation shows up as 99.99%

Expected: Should be 100%

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/30e5a810-8e1c-4e22-a0ea-ff8063ede4a6)

**Comment by rkzel** [comment]
This appears fixed in the new-style DV.
