### ISSUE TITLE
Write clear documentation per app

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1211]
Include:
    - How to use the apps
    - How to install the apps
    - Definitions of each permission
    - Warnings, limitations, setup recommendations

Progress check:
- [ ] Address Book
- [ ] Allocations
- [ ] Projects
- [ ] Dot Voting
- [ ] Rewards

**Comment by javieralaves** [comment]
Closing this in favor of more granular issues that'll be associated to a documentation epic.
