### ISSUE TITLE
Improve input validations and check them with the designs

### ISSUE THREAD

**Issue by ottodevs** [AutarkLabs/open-enterprise#1232]
We would probably want to improve some of the current validations for inputs on different apps, in case those validations should eventually trigger Info messages, it would be nice to have them referenced in the designs, so the developers won't need to take responsibility of deciding about which component to use, its position, color, text format and so, that would save some time eventually and make our apps more consistent.

There are already some of these designs on Figma, but there are lots of other fields that could need additional messages in case of failed validations.

Also in the cases where validation is performed on typing, disabling the submit button, those cases should be specified as well.

**Comment by jayalaves** [comment]
@ottodevs I've been working on making improvements to the way I set up design specifications, and one aim in particular was to make input validation specifications more relevant. You can see these already for [Projects](https://www.notion.so/autark/Projects-da6e4f8e33e34df8b325d625a1b9dd18), [Allocations](https://www.notion.so/autark/Allocations-ec0da2888cd14bea996fd5f0e935d116), and [Rewards](https://www.notion.so/autark/Rewards-4e1da447801c4cf1869328e882d56c4a). Let me know what you think!

**Comment by jayalaves** [comment]
@stellarmagnet @ottodevs All design specifications now cover input validation patterns:
* [Address Book](https://www.notion.so/autark/Design-specifications-6fe12da6601241029d104e8f9f74ef3e#50f494b977014cecb7fb85173e9a8353)
* [Allocations](https://www.notion.so/autark/Design-specifications-cf909372d4f044898da2278fa9bdb4c9#5f1de736f6e94ce5aff9313f0928ff24)
* [Projects](https://www.notion.so/autark/Design-specifications-49beb20804de4552b1f6fb81ef0ce551#bb8fa05c93ba4d7bb6f2d33df9a9ad80)
* [Rewards](https://www.notion.so/autark/Design-specifications-fdb1c20d8adc48c6971a1760ef2c0248)
I think we're safe at this point to close this issue unless you have any further comments!

**Comment by jayalaves** [comment]
I'll be closing this issue as it's been assigned to me and as far as the specs go there's been an improved documentation of the input validations. If you have any further questions about this let me know.
