### ISSUE TITLE
Dot Voting UX issues

### ISSUE THREAD

**Issue by chadoh** [AutarkLabs/open-enterprise#1234]
Part of #1114 

- [x] **search bar disappears on narrow screens** _skip this for now, following Voting app's lead_

    ![searchbar disappears on narrow screens](https://user-images.githubusercontent.com/221614/64735180-0a181e80-d4b6-11e9-910d-1365a03db58e.gif)

- [x] _**filter option boxes have blue outline on first load, as if active**_
- [x] _**filter bar disappears when no match**_

    ![search bar disappears when no matches](https://user-images.githubusercontent.com/221614/64735301-4ea3ba00-d4b6-11e9-87e3-a86381c95604.gif)

- [x] **"You: NaN%"**

    <img width="745" alt="Screen Shot 2019-09-11 at 16 52 50" src="https://user-images.githubusercontent.com/221614/64735327-595e4f00-d4b6-11e9-9619-e1ee49375c36.png">

- [x] **Changing vote: slider not present**

    ![change vote](https://user-images.githubusercontent.com/221614/64735177-097f8800-d4b6-11e9-9e99-cf407811f464.gif)

- [x] **Vote Details not updated on vote close** – _blocked by https://github.com/aragon/aragon.js/pull/361 (ok, not fully blocked, but our solution will be much more robust once we have that, and there's not much point in implementing this until we have it)_

- [x] **Cast Vote UI disappears when sidebar opens**

    ![voting ui closes when side panel opens](https://user-images.githubusercontent.com/221614/64735181-0a181e80-d4b6-11e9-8cbb-ca2178e4207f.gif)

- [x] **"Participation" does not update after I cast my vote**

- [x] **Voting options should use `IdentityBadge` component**

- [x] **Get rid of always-empty "Description"** section; get **rid of vote # from VotingCard**. Design:

    <img width="1440" alt="Screenshot 2019-09-12 at 19 25 03" src="https://user-images.githubusercontent.com/221614/64810995-6dfc1f00-d56a-11e9-90ad-d20535494203.png">

* [x] **fix vote-count vertical centering**

    <img width="139" alt="Screen Shot 2019-09-12 at 13 16 00" src="https://user-images.githubusercontent.com/221614/64805615-8286ea00-d55f-11e9-99e1-851b0490e687.png">

* [x] **fix VotingCard styling with long descriptions**

   <img width="277" alt="Screen Shot 2019-09-12 at 13 28 28" src="https://user-images.githubusercontent.com/221614/64806505-494f7980-d561-11e9-858a-4078a255ace7.png">

**Comment by e18r** [comment]
I'm checking that the associated PR indeed solves all the issues outlined here. I'm setting in **bold** those issues that I'm able to reproduce, and then in _**italic bold**_ those issues that the associated PR solves.

**Comment by ottodevs** [comment]
> I'm checking that the associated PR indeed solves all the issues outlined here. I'm setting in **bold** those issues that I'm able to reproduce, and then in _**italic bold**_ those issues that the associated PR solves.

Wondering if you would like to take a bit of time explaining the procedure you used to reproduce the issues, I couldn't make it work on my local environment, since there is no current way to create DotVotes

**Comment by e18r** [comment]
I was reproducing the issues on `dev`, but when I switched to this branch to check that the issues were solved, I encountered the same problems as you. Now @chadoh updated the branch and Allocations is working.
