### ISSUE TITLE
Address Book Tweaks

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1265]
- [x] On Address Book, right-align the Type column so it's closer to the context menu

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/4d2afb3f-fe29-43d2-a6f5-8920e05ac8e0)

Look at Tokens for inspiration -
![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/53efc936-27ca-4cff-adf5-102515ba8819)

- [x] `force` the address for the LocalIdentityBadge (the custom label should not display)
![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/61c2058a-a2a8-4acf-ad3c-42f0321fa868)

**Comment by lcoenen** [comment]
The first one looks like a bug in `aragon-ui`. The difference between the Token Manager view and the Address Book is the last `<td>` element width. In the Token view, it's set to `1px`, while it's set to 0 in the Address Book. 

![image](https://user-images.githubusercontent.com/1237971/65893055-3df0b080-e39f-11e9-8b86-663a758366b6.png)
![image](https://user-images.githubusercontent.com/1237971/65893105-5234ad80-e39f-11e9-9a3d-19af13148c6c.png)

Indeed, setting the width to `1px` fixes the issue. It seems this property is set in [here](https://github.com/aragon/aragon-ui/blob/newstyle/src/components/DataView/TableView.js), lines 302-... (in the `<EntryRow>` component)

```
              width: ${compact
                ? '1px' // For some reason Blink tends to make 0 grow but not 1px
                : 'auto'};
```

The `compact` property is supposed to be set to `true` by `cellsFromEntry()` used in `Entry`, if it receive either `hasAnyExpensions` (which should be our case here - [see this line](https://github.com/aragon/aragon-ui/blob/2e57e6986f87d7e8182a00119ca0b372ee597812/src/components/DataView/TableView.js#L67) )

**Comment by e18r** [comment]
@lcoenen Thank you for the explanation. Do you believe it can be fixed by means of a workaround? Also, we're not using the very last version of AragonUI at the moment. Does this get solved in the latest version?

**Comment by lcoenen** [comment]
I'll checkout today what's going on exactly. Maybe we can just set the last
td of that specific page - it would be a hack. I'll let you know as soon as
I have more infos.

**Comment by lcoenen** [comment]
@e18r Indeed, the tweak in question was done after the `alpha-19` version we're using, so it looks like upgrading would fix the issue :D

**Comment by e18r** [comment]
Then let's just wait for the upgrade instead of hacking it. As for the second item in this issue, have you got the time to check it out? Thank you!

**Comment by lcoenen** [comment]
On it :)

**Comment by lcoenen** [comment]
See https://github.com/AutarkLabs/open-enterprise/pull/1274

**Comment by e18r** [comment]
@lcoenen I just submitted a PR for the upgrade of AragonUI in Address Book: https://github.com/AutarkLabs/open-enterprise/pull/1277
