### ISSUE TITLE
Allocations history looks different than designs

### ISSUE THREAD

**Issue by ottodevs** [AutarkLabs/open-enterprise#1346]
The implemented UI looks different than the designs.

This is the result of the work here:
![image](https://user-images.githubusercontent.com/5030059/66770482-b2286980-eef2-11e9-8d59-0c67e8d57397.png)

Compared to our original designs:
![image](https://user-images.githubusercontent.com/5030059/66770517-c704fd00-eef2-11e9-9d2e-dd52b65c036b.png)

- [ ] Background color of expanded area is different
- [ ] Paddings and margins seem different
- [ ] Sizes of elements
- [ ] Budget column shows id instead of budget description
- [ ] Amount column has negative sign
- [ ] Alignment of columns
- [ ] Expand button position and chevrons are different
- [ ] Background color of each candidate is different
- [ ] Progress bar position should be to the right instead of below
- [ ] Some amounts are wrapped by parenthesis in the design (confirm the correct format of this with @jayalaves )

**Comment by jayalaves** [comment]
@ottodevs Thanks for referencing these needed changes! I wasn't expecting the expanded row views to be scoped for this week, so I considered any additional work as helpful and worth tackling later on, but if we can cover it now, much better. Some things to add...

- Note that in the latest changes, we've updated the styling for the amounts, as shown [here](https://www.figma.com/file/9c4GAhAa1LhH1TmJC8vCHA/Allocations?node-id=696%3A17927)
- I'll adhere to including the expand button in the designs too, so no need to remove that; doing so, expect that the columns will have less horizontal space, so I'll probably end up being more flexible with the space for the badges in the expanded rows
- Is there any reason why the progress bar can't be below the address as in the design?
- Correct format is no parentheses, typo! Thanks for the catch!

**Comment by jayalaves** [comment]
See latest changes on [Figma](https://www.figma.com/file/9c4GAhAa1LhH1TmJC8vCHA/Allocations?node-id=713%3A970).

**Comment by stellarmagnet** [comment]
Based on the current implementation, i think it matches closely to designs. Closing this issue. @jayalaves if there are padding/spacing or color changes, please capture anything missing in a separate ticket.
