### ISSUE TITLE
Truncation issues for Fund Issue panel

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1371]
- [ ] In Firefox, the issue name is not being truncated. This means we wont be able to see the bounty amount

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/ff0311c7-3a66-4854-9ad6-61763102ebfa)

- [ ] The left margin with the icon should remain fixed, so the text doesn't move when truncated. Additionally, we should always reserve empty space for the amount badge such that the truncated amount of characters doesn't change once you type in hours.
![fundpanel](https://user-images.githubusercontent.com/2584493/67202828-dc55bc00-f409-11e9-9022-0b19a9157468.gif)

**Comment by javieralaves** [comment]
Truncation works as expected but the slight repositioning when the amount appears persists. Closing this for now and will address it in a future update since this is an older issue.
