### ISSUE TITLE
Cannot select token for Base Rate in Project Settings

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1372]
Only ETH is showing up:
https://beta.autark.xyz/#/oe-demo/0xf1c7d9fea39b3fae66358f0b595b175a03828ccc

**Comment by stellarmagnet** [comment]
This looks like it works after I deposit a DEV token into finance, even though finance already had DEV tokens. Why does this need to occur?

**Comment by PeterMPhillips** [comment]
@stellarmagnet I can't seem to replicate this issue. If I transfer or mint directly to the Vault, it doesn't show up in the Finance app or the Projects app. If I transfer it using the Finance app, it shows up in both Finance and Projects. I can't create a scenario where funds are displayed in the Finance app but not Projects. I feel like this might be a caching issue, however, when logging the cachedState and force mining the chain, the DEV token still appears in the cacheState as long the token was transferred using the Finance app. Any suggestions on how to replicate?
