### ISSUE TITLE
Fix the color of the "more" badge in allocations card

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1381]
This doesn't seem to match up with the Figma, i don't think
![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/c339e94b-2d5d-47b2-adc8-47a10d4d9b60)

**Comment by javieralaves** [comment]
Tested this in the continuous deploy from December 17th, 2019.

✅ Everything looks as expected!
