### ISSUE TITLE
New Project panel UI tweaks

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1387]
- [x] Search text should just be "Search" like all the others.
- [ ] Center radio button with respect to text container.
- [ ] Center repo text with respect to text container.
- [ ] By default, text container should be 48px in height.

**Comment by rkzel** [comment]
Simplest thing is done. Placement of text, buttons, etc is difficult, because we use aragon-ui component for the list of repos, and it's not exactly configurable. If current look is insufficiently good we can always clone and improve locally?
