### ISSUE TITLE
Move the Status widget above the Participation widget and remove unnecessary text

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1389]
- [ ] Move the Status widget above the Participation widget
- [ ] Remove unnecessary "status" text - It should not say "status" inside the box

![image](https://user-images.githubusercontent.com/2584493/67236093-d3d0a600-f448-11e9-937f-3b5c066ff801.png)

**Comment by javieralaves** [comment]
Looks good!
