### ISSUE TITLE
Show the amount of tokens per Allocation option (Dot Voting results)

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1390]
Once the vote is finalized, show the amount of tokens per option, in the Dot Voting UI.

(looks like this wasn't implemented)

https://www.figma.com/file/NZQk49jsqKMHdWxsEwSxJs5n/Dot-Voting?node-id=832%3A7917

**Comment by javieralaves** [comment]
Tested this in the continuous deploy from December 17th, 2019.

✅ Everything looks as expected!
