### ISSUE TITLE
Allocations: Editing a budget to change the token doesn't work

### ISSUE THREAD

**Issue by PeterMPhillips** [AutarkLabs/open-enterprise#1402]
If you create a new budget using a one token, and then edit the budget to use another token, a call is made to the contract but the new token isn't displayed on the front-end, even if you reload the page.

How to recreate:
- In the allocations app, create a new budget. Set the budget to any number and set the token to ETH
- After confirming the transaction the new budget will appear on the page. In the top corner press the dropdown button and press 'Edit'
- In the panel change the budget token to a different token that is held in the Vault (in my case I transferred 1 AUTD in the Finance app)
- After submitting the change and approving the transaction, the budget should update with the new token but doesn't.

I suspect the issue is because we are not catching an event in the app script but I haven't looked into it yet.

**Comment by stellarmagnet** [comment]
The token should not be updatable. This needs to be a read only value for the token name, not a dropdown.
