### ISSUE TITLE
Allocation displays as Approved even though it is Enacted

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1420]
![image](https://user-images.githubusercontent.com/2584493/67390009-08a14200-f59c-11e9-8e49-b51ba713ff2d.png)

**Comment by topocount** [comment]
Has it been verified that the ETH has been transferred to all entities? It shouldn't show as enacted until all transfers are complete based on the code right now

**Comment by stellarmagnet** [comment]
Cannot reproduce
