### ISSUE TITLE
Improve error message and/or validation?

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1421]
* Change the icon: Use the “Caution” icon from aragon-ui - the color should be theme.OrangeDark
* Change the message: While you selected a recurring dividend, based on your parameters, there will only be a single disbursement.
* The action behavior: Still allow the user to submit the reward.

![image](https://user-images.githubusercontent.com/2584493/67392019-148f0300-f5a0-11e9-9231-4c961c372add.png)

**Comment by e18r** [comment]
> Currently says:
> 
> > Disbursement frequency does not output any disbursements for the given time range.
> 
> Should say
> 
> > The balance of available funds is less than the proposed dividend schedule. Please change the amount or frequency.

@stellarmagnet The balance has nothing to do with this error. It's merely about the relationship between the disbursement frequency and the start and end dates. @jayalaves any suggestions? Mine would be

> Please choose a longer date range or a shorter disbursement frequency in order to have at least two disbursements.
