### ISSUE TITLE
When funding model is fixed, conditionally render how difficulty is set

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1430]
On Settings tab, when Funding Model is Fixed, remove the difficulty multiplier numbers, as shown in [the design](https://www.figma.com/file/Xnn4lQJX4d5AautuvmAlnxHf/Projects?node-id=1181%3A14)

<img width="572" alt="Difficulty levels: Easy, Normal, Hard" src="https://user-images.githubusercontent.com/221614/68897564-c3d07d00-06fb-11ea-8d59-16b3bbf2dab1.png">

**Comment by javieralaves** [comment]
Looks good!
