### ISSUE TITLE
Improve spacing of issue tile in mobile

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1438]
Increase the padding below the first line
![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/3ca4609c-181d-404e-9f15-839f11b8c386)

**Comment by stellarmagnet** [comment]
This doesn't seem to match up with what we have in Figma... The original ticket didn't describe enough what was wrong, but Figma should be considered the typical source of truth!

Currently looks like this:

![image](https://user-images.githubusercontent.com/2584493/68421045-62843900-0152-11ea-8ee3-b40e40b9a2c9.png)

Figma: https://www.figma.com/file/Xnn4lQJX4d5AautuvmAlnxHf/Projects?node-id=983%3A382

**Comment by javieralaves** [comment]
Tested this in the continuous deploy on December 17th, 2019. Looks good!
