### ISSUE TITLE
Remove Opened By and change Time Until Due

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1440]
* Remove "Opened by" in both versions of the detail view (with bounty * without)
* Time until due should be more like "4 days" or "4 days ago" (past) -- like we had before
remove opened by -- should just be two columns

After making changes, please test responsive behavior.

![image](https://user-images.githubusercontent.com/2584493/67480072-91cd7d00-f65f-11e9-97d5-4bdcc86cc986.png)

![image](https://user-images.githubusercontent.com/2584493/67585158-4db9a580-f74f-11e9-8922-9bc86b3d5506.png)

**Comment by javieralaves** [comment]
Looks as expected!
