### ISSUE TITLE
Dot Voting: no "syncing" message during initial sync

### ISSUE THREAD

**Issue by chadoh** [AutarkLabs/open-enterprise#1447]
When I first load Dot Voting in a new browser, while the data is synced from on-chain, we do not see a "syncing" message as in other apps. It appears as if there are no votes, until they suddenly start popping in.

**Comment by PeterMPhillips** [comment]
https://github.com/AutarkLabs/open-enterprise/pull/1499

**Comment by javieralaves** [comment]
Tested this in the continuous deploy from December 17th, 2019.

✅ Everything works as expected!
