### ISSUE TITLE
Populate details.md for the apps

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1462]
Populate details.md file for the apps, so app center has feature list

**Comment by jayalaves** [comment]
Draft text ready for review [here](https://docs.google.com/document/d/1Mn7LVY4CpyYoAKWk4DH6cuNK2Ns0qGcGhm7y5Ck0aJw/edit?usp=sharing).

**Comment by stellarmagnet** [comment]
This was done
