### ISSUE TITLE
Rewards: date picker appears in wrong location

### ISSUE THREAD

**Issue by pythonpete32** [AutarkLabs/open-enterprise#1469]
**Describe the bug**
The start date picker appears in the same location as the end date picker to the far right of the screen. This seems a.but unnatural

**Mainnet or testnet?**
Rinkeby

**Organization**
https://rinkeby.aragon.org/#/aarontest01

**To Reproduce**

1. Go to 'Redemptions'
2. Click on 'start date'
3. See error

**Expected behavior**
I expect the date picker to appear underneath the start date button

**Screenshots**
![image](https://i.ibb.co/s16Kmx9/Screenshot-20191026-185542.png)

**Desktop (please complete the following information):**
 

**Smartphone (please complete the following information):**
 - Samsung S4,  Opera 54.0.2673

**Additional context**

**Comment by javieralaves** [comment]
Works as expected now.
