### ISSUE TITLE
Rewards: blank screen where transaction prompt should appear

### ISSUE THREAD

**Issue by pythonpete32** [AutarkLabs/open-enterprise#1470]
### Describe the bug
After completing the form and submitting, instead of a transaction prompt the screen goes blank. Even after waiting several minutes, nothing happens

### Mainnet or testnet?
Rinkeby

### Organization
https://rinkeby.aragon.org/#/aarontest01
https://rinkeby.aragon.org/#/aarontest03

### To Reproduce
1. Go to 'Redemptions'
2. Select 'Dao token as reference token'
3. Select 'reoccurring dividend'
4. Select '1 eth per disbursement'
5. Select 'tomorrow as start date and three months later as end date
6. Press 'continue '
7. See error

### Expected behaviour
A transaction to appear and the elements to remain on the screen until it transitions

### Screenshots
![image1](https://i.ibb.co/cxqKQq3/2019-10-28-113520-1920x1080-scrot.png)
![image2](https://i.ibb.co/W5h6KKC/2019-10-28-113551-1920x1080-scrot.png)

### Desktop (please complete the following information):
 - OS and OS version: Ubuntu 16.04.3 LTS
-  Browser: Brave Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)

### Smartphone (please complete the following information):
• Samsung S4, Opera 54.0.2673

**Comment by topocount** [comment]
Thanks @pythonpete32 I just replicated this in a dev environment. Will have a fix out soon

**Comment by topocount** [comment]
@pythonpete32 we've merged a fix for this issue. We'll publish this fix to rinkeby and update this issue when that is complete

**Comment by javieralaves** [comment]
This issue no longer exists :)
