### ISSUE TITLE
Fund issues: Past deadlines & unable to continue

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1485]
* Validation message for past deadlines: "Deadline must occur in the future."
* Unable to click on the 'Fund issue' button to proceed even after inserting all the required info

**Comment by javieralaves** [comment]
@PeterMPhillips I'm not able to reproduce this enhancement. Also, I'm unable to proceed with funding an issue even after inputting all the required information.

![Screenshot 2019-12-13 at 10.24.21.png](https://images.zenhubusercontent.com/5cf4fe30c7859b3c51c81634/1bed1113-b321-47cc-a410-d21d1114c33b)

**Comment by javieralaves** [comment]
Putting this issue into the 'Upcoming' pipeline so we can tackle it soon, and updated the description to cover also the bug of not being able to move forward after inserting all the required info.

**Comment by PeterMPhillips** [comment]
@javieralaves I can't reproduce this issue in the `dev` branch. Could you confirm that it still needs fixing and steps to reproduce?

**Comment by javieralaves** [comment]
@PeterMPhillips @stellarmagnet Just reviewed this on Rinkeby and it looks good to go now!
