### ISSUE TITLE
Issues should have funding amounts or hours that are greater than 0

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1487]
We need to validate that for every issue the user selects for funding, that the user inputs either some hours or amount that is > 0.

We can have validation message on submit that says "Funding amounts must be greater than zero."

This should be an okay validation message for both use cases (amounts/hours) for now. We can always re-evaluate and refine later.

cc @jayalaves

**Comment by jayalaves** [comment]
@stellarmagnet 

On Hourly, we already have an automatic validation catch inherited from HTML that says that the amount must be larger than 1e-18, or essentially zero, when zero or lower input is specified. Maybe we can have the exact same validation catch for fixed amounts? And in this case, we don't even need to care about additional validation error displays.

**Comment by javieralaves** [comment]
Not getting any errors for this behavior, this issue could be related to #1485. Removing from this epic to close the epic and moving the issue to 'Upcoming' to address this at a later time.

![Screenshot 2019-12-13 at 10.33.08.png](https://images.zenhubusercontent.com/5cf4fe30c7859b3c51c81634/531022af-9b6e-4e29-bdc2-fbfcbc104274)

**Comment by PeterMPhillips** [comment]
@javieralaves the `dev` branch currently validates the amount, disables the submit button, and gives an error message if the user types 0. Please confirm whether this issue is still valid.

**Comment by javieralaves** [comment]
Confirming this, thanks @PeterMPhillips!
