### ISSUE TITLE
Cannot request assignment unless I populate estimated hours & date

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1492]
* These fields should not be treated as required
* In the review application UI, display a `-` if these fields were not populated. We should not treat the default date as it being populated.
![image](https://user-images.githubusercontent.com/2584493/67817622-4d7d1b00-fa6b-11e9-910f-411d7f3a147f.png)

**Comment by javieralaves** [comment]
Works as expected!
