### ISSUE TITLE
Submit work - panel enhancements

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1493]
* Reduce the height of the "additional comments"input,  so it's the same height as "proof of work" box
* The user *should not* be required to input hours to submit work
* Reword the 2nd checkbox to "I understand that reporting hours is for informational and planning purposes only."
* Reword the placeholder text of the "Proof of Work" input to: "Add a link to your work, such as a document or a pull request."

**Comment by javieralaves** [comment]
Looks as expected.
