### ISSUE TITLE
"Submit work" UI is a bit confusing when it's in the stage where it's waiting for a work submission

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1494]
For issues that require application approval -- once an application is approved, technically, we are only accepting work from *one account*/address, correct?

The current UI will make it seem like *anyone* can submit work.

Is there a way to do validation to have "submit work" only enabled for the account that got approved?

cc @jayalaves

**Comment by jayalaves** [comment]
@stellarmagnet 

Is there a way to keep track of the approved worker address and vary the information displayed on the Status widget based on that? My first suggestion would be to be a step ahead of any form of validation and display the right information to the user based on whether they are the approved worker or not. The approved worker would see the "Submit Work" button; other addresses would only see a text "Work in progress by [the approved address]."

**Comment by stellarmagnet** [comment]
> @stellarmagnet
> 
> Is there a way to keep track of the approved worker address and vary the information displayed on the Status widget based on that? My first suggestion would be to be a step ahead of any form of validation and display the right information to the user based on whether they are the approved worker or not. The approved worker would see the "Submit Work" button; other addresses would only see a text "Work in progress by [the approved address]."

I think so -- please check with development.

**Comment by jayalaves** [comment]
Conditional designs are possible – please have a look at [my sketched proposal](https://www.notion.so/autark/Improve-bounties-UX-134d8bcec6cc4a0882a88e8f94e7222c#950214ffcbb746ed9579b58a5f11b061) for the new Status widget pattern, depending on the general state of the bounty and who's viewing it.

**Comment by jayalaves** [comment]
Latest designs [on Figma](https://www.figma.com/file/Xnn4lQJX4d5AautuvmAlnxHf/Projects?node-id=1181%3A14) now reflect full support for conditional components based on the viewer status.
