### ISSUE TITLE
Inconsistent stubbed api behavior in Brave and Firefox

### ISSUE THREAD

**Issue by topocount** [AutarkLabs/open-enterprise#1502]
I did the following steps:
- Fetch, checkout and pull this branch
- Run `npm prune && npm i`(just in case)
- `npm run frontend:dot`

Then I receive this error, and the screen is completely empty:
![image](https://user-images.githubusercontent.com/5030059/67965867-1f324380-fc03-11e9-8566-08588cfd0ecc.png)

As you can see I tried to debug some variables and yeah as you can see, the issue is that executionTargetData is not present in the vote.data:
![image](https://user-images.githubusercontent.com/5030059/67966200-b9928700-fc03-11e9-8388-4d7f70707fcc.png)

Also, is it really needed to have these duplications? like metadata and description, for example...

I tried to create some votes but does not change the situation.

After some testing, I found that in brave `api.createVote()` returns an observable, while in firefox it works as it should (creating the vote), I fix in brave by changing it to: `await api.createVote().toPromise()`

I am not really sure if the actual issue is because there is some old cache, although I tried to clean the chache.

_Originally posted by @ottodevs in https://github.com/AutarkLabs/open-enterprise/pull/1472#issuecomment-548467670_

**Comment by ottodevs** [comment]
Clarified by Chad, it was a local env issue (clearing localStorage fixes the issue)
