### ISSUE TITLE
Should be able to submit an application after others have submitted one

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1504]
Right now, as soon as one person applies for a bounty, nobody else can apply. The "submit application" action is not visible. We need to make this action visible during the "Pending application review" status.

cc @jayalaves - I find the specs on Notion kind of confusing around this, is it possible to write up something light-weight in this ticket?

This is somewhat related to: https://github.com/AutarkLabs/open-enterprise/issues/1494

Also, we may want to have some of the pending icons in the status region, with color etc.

Current mockup:
![image](https://user-images.githubusercontent.com/2584493/68007644-70f5c080-fc39-11e9-8ff4-278e455ccfb0.png)

**Comment by jayalaves** [comment]
Let's go through the bounty process designs:

### No bounty

<img width="1440" alt="D 2 3 - Issue - Not Funded" src="https://user-images.githubusercontent.com/28843778/68013679-db385080-fc8d-11e9-9404-9b2ee5fa5fc7.png">

In this case, the only interaction point is the context menu, and the option should be:

- "Fund" with coins icon

Once a funding submission is approved, we move to our next state.

### Accepting applications

<img width="1440" alt="D 2 4 - Application Review - Accepting" src="https://user-images.githubusercontent.com/28843778/68013823-3c602400-fc8e-11e9-84dd-6f4ff94c8d1e.png">

As funding is approved, Status is enabled, and with it a handy button to submit an application. The context menu should also display:

- "Submit application" with file icon
- "Update funding" with coins icon
- "Remove funding" with cross icon

Not sure if those last one has been scoped yet, but either way that's the vision.

<img width="1440" alt="D 2 4 2 - Application Review - Received" src="https://user-images.githubusercontent.com/28843778/68014176-0ff8d780-fc8f-11e9-850a-a808f4e289b7.png">

As soon as at least one application has been received, and until any application has been approved, the Status section gains an extra button for reviewing existing applications, and the context menu gains an option underneath "Submit application":

- "Review applications" with eye icon

Once an application is approved, we move to our next state.

### Work in progress

<img width="1440" alt="D 2 4 3 - Work in progress" src="https://user-images.githubusercontent.com/28843778/68014238-3b7bc200-fc8f-11e9-8a2c-5507ceb5b25e.png">

At this point, an application has been approved and we're simply waiting for the contributor to submit work. Status displays the "Submit work" button**, and the context menu options would be:

- "Submit work" with lightning icon
- "Cancel work" with cross icon

Not sure if cancelling one's work commitment to a bounty is deployable at this point, but that's the vision for upcoming releases.

And lastly, once the work has been submitted, we're at our final stage.

### Review work

The work has been submitted and is ready to be reviewed. Status displays the "Review work" button, and the context menu option also*** has that option:

- "Review submission" with eye icon

** Note: The user experience will improve as soon as we implement changes with conditional UIs that keep track of the address' context with respect to the issue. I may have started to design those changes today, to be introduced by early next week.
*** This may be redundant and unnecessary at this stage. 

Let me know if this clarifies doubts regarding the general functionality at each stage of the bounty process. I'll be fine-tuning this process throughout the next few days to introduce conditional UI logic and a more descriptive Status section introducing icons.

**Comment by stellarmagnet** [comment]
@jayalaves we also need the usecase for "fulfilled"

i think the user should be able to - review (past) applicants and review (past) work

right now the context menu exists but cannot select anything

![image](https://user-images.githubusercontent.com/2584493/68063152-0cd00c80-fccc-11e9-9f8f-6174e22b1c59.png)

**Comment by jayalaves** [comment]
@stellarmagnet Okay, I've just added a tiny specification change to [Notion](https://www.notion.so/autark/Design-specifications-49beb20804de4552b1f6fb81ef0ce551#745e4fe76f68493fa15143c4c243ff20) to reference that under that state we should have "View submission" with the eye icon. Let me know if that makes sense!
