### ISSUE TITLE
Feedback field too tall

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1505]
This seemed to really grow, let's choose a consistent height for this that conforms with the rest of the multi-line inputs in projects

![image](https://user-images.githubusercontent.com/2584493/68008002-9636fe80-fc3a-11e9-851e-5e4141929ffd.png)

**Comment by jayalaves** [comment]
The height that we have specified in the designs is 80px. Also, I've noticed that it's missing a handle on the bottom-right corner for resizing if needed.

**Comment by Quazia** [comment]
I'm adding some extra time in here just to account for potential back and forth around whether the solution adheres to design expectations.

**Comment by javieralaves** [comment]
Looks good!
