### ISSUE TITLE
Quality badge seems incorrect in "review work" panel

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1506]
![image](https://user-images.githubusercontent.com/2584493/68008090-eca43d00-fc3a-11e9-87aa-b4666a528e07.png)

**Comment by Quazia** [comment]
Please report back once the root cause and solution approach is known for this issue, it may be more complex than estimated.

**Comment by javieralaves** [comment]
Looks good!
