### ISSUE TITLE
Improve state management after a reward is claimed

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1518]
- In My rewards: i claimed a reward, and the row for the reward disappeared after i claimed it
- I left the tab and returned to it, and then I see the reward in "Claimed" status

Expect: I expect to see the reward as "Claimed" as soon as I claim it

**Comment by e18r** [comment]
Unable to reproduce:
![Peek 2019-11-05 10-48](https://user-images.githubusercontent.com/16065447/68222982-ef47bf00-ffb9-11e9-9953-ff877e7bcb9c.gif)
Tested locally on latest dev
cc @stellarmagnet

**Comment by stellarmagnet** [comment]
Okay, will close this for now then!

**Comment by stellarmagnet** [comment]
I was able to reproduce it on this DAO: https://rinkeby.aragon.org/#/neudune/0xc5e05c810166af221c2fc79cee2d0a7f288d6a42

**Comment by stellarmagnet** [comment]
![rewards](https://user-images.githubusercontent.com/2584493/68442356-9593f000-0185-11ea-8e5d-dc5edac21c30.gif)

**Comment by e18r** [comment]
I'm having some issues using that Rinkeby DAO in order to diagnose the problem. Will come back at it later.
