### ISSUE TITLE
Make it possible to give ERC-20 rewards

### ISSUE THREAD

**Issue by john-light** [AutarkLabs/open-enterprise#1525]
**Is your feature request related to a problem? Please describe.**
Right now I can only create rewards in ETH.

**Describe the solution you'd like**
I want to be able to create rewards in ERC-20 tokens too.

**Additional context**
There is a dropdown next to "amount per disbursement" that makes it seem like I can select more than just ETH for rewards. But even though my org's vault has a balance of SWT, the dropdown only shows ETH as an available token for rewards.

Org used: https://rinkeby.aragon.org/#/openorgtest/

**Comment by stellarmagnet** [comment]
How did you deposit the SWT into your vault?

**Comment by john-light** [comment]
@stellarmagnet  airdrop from the test tokens feature

**Comment by stellarmagnet** [comment]
Okay, I think that the airdrop doesn’t trigger an event such that the app knows that the token exists in the vault.

ERC-20 token rewards are definitely possible, the limitation right now has to do with the logic in populating the dropdown.

You’ll see that if you deposit tokens into the Finance app via the New Transfer action, you will then see the token as an option in rewards. Let me know if that works!

**Comment by john-light** [comment]
> I think that the airdrop doesn’t trigger an event such that the app knows that the token exists in the vault.

Interesting, the allocations app recognizes the SWT token in the vault.

**Comment by stellarmagnet** [comment]
> > I think that the airdrop doesn’t trigger an event such that the app knows that the token exists in the vault.
> 
> Interesting, the allocations app recognizes the SWT token in the vault.

Ahh, good to know. @topocount can you investigate more the logic differences in the dropdowns?

**Comment by stellarmagnet** [comment]
Not seeing this as resolved yet, re-opening
