### ISSUE TITLE
Unable to cast a vote to create a new reward

### ISSUE THREAD

**Issue by john-light** [AutarkLabs/open-enterprise#1526]
**Describe the bug**
I have created a proposal to create a new reward but am unable to cast a vote for this proposal, despite the voting app showing clearly that I have the ability to cast a vote. Get an error "Action impossible".

**Mainnet or testnet?**
testnet

**Organization**
openorgtest.aragonid.eth

**To Reproduce**
1. Create a reward -> create a proposal to create a reward
2. Go to voting app and try to vote on the proposal
3. Notice that you cannot vote to create the reward

**Expected behavior**
I expect to be able to cast my vote to approve or reject creating the reward.

**Screenshots**

![Screenshot_2019-11-02 Aragon(2)](https://user-images.githubusercontent.com/9424721/68078690-c05efc80-fdb1-11e9-8fb3-a6d6817276d2.png)

![rewarderror](https://user-images.githubusercontent.com/9424721/68078696-e4224280-fdb1-11e9-8e3a-1aea313db86f.png)

**Comment by stellarmagnet** [comment]
Does ETH exist in your vault?

Link to your DAO?

**Comment by stellarmagnet** [comment]
Can you share more details with what your selections were in the New Reward panel and what is displayed in the confirmation screen?

**Comment by john-light** [comment]
Reference asset: Other 
Token address: ORG token contract address
Type: Recurring dividend
Amount: 0.01 ETH
Duration: From today til Feb 4, 2020, 1x per week

What is shown on the confirmation screen:

![Screenshot_2019-11-02 Aragon(4)](https://user-images.githubusercontent.com/9424721/68079031-d91ee080-fdb8-11e9-8719-1d61dfced4df.png)

![Screenshot_2019-11-02 Aragon(5)](https://user-images.githubusercontent.com/9424721/68079036-dcb26780-fdb8-11e9-9a56-de237bb250f9.png)

**Comment by stellarmagnet** [comment]
Good find @john-light!

This seems to be related to how we pass in the date for recurring dividends, with respect to when it should actually begin.

For recurring dividends, the first one will occur at the end of first interval, e.g. in your case -- it should have actually attempted to start them on November 10th instead of November 3rd. 

We will make an update to the UI (and radspec) so this is all more clear that the first disbursement is *at the end* if the first interval, which is start date + interval length.

Dividends should still work properly for one-time.

Let me know what you think, as we are evaluating if in the future, we should restructure how we handle disbursements for recurring dividends in the contract (whether start of cycle is expected, or end of cycle - for the first disbursement).

**Comment by john-light** [comment]
> Let me know what you think from a UX perspective

1. Most importantly, I think you should not allow users to attempt an "illegal" or "invalid" action. The reason I could not vote on the proposal seems to be because the date-picker allowed me to choose the current day (or, depending on how it's deciding what day it is, a day in the past) as my start date. I think the date-picker should only allow me to pick a start date that is valid so that I (and other tokenholders) will actually be able to vote on the proposal.

2. I think if you put a note somewhere that says something along the lines of "The first reward under this policy will be disbursed [chosen interval e.g. one week] after your chosen start date, and repeat every [chosen interval] until your chosen end date" then that should make it clear enough how it works. Then the disbursement dates on the confirmation screen make it unambiguous as to when each disbursement will happen.

**Comment by topocount** [comment]
> Then the disbursement dates on the confirmation screen make it unambiguous as to when each disbursement will happen.

@john-light  Because we didn't want to rely on any service to calculate the vesting time of an award, we decided to utilize block numbers under the hood. Would you want to see the specific block number when the award will be available next to the date?

**Comment by john-light** [comment]
@topocount Adding something like (Block XXXXXXX) would fully disambiguate when disbursements happen. Right now the date is approximate, and no time zone is given, so having the most precise measurement possible (in this case, block time) would be useful, if only for debugging purposes imo.
