### ISSUE TITLE
Explain what granting GitHub permission to the Projects app entails

### ISSUE THREAD

**Issue by john-light** [AutarkLabs/open-enterprise#1528]
When I go to log in to GitHub from the Projects app, it seems to be asking for quite a lot of permissions that I would frankly be entirely uncomfortable granting to any centralized app. The Projects app documentation does not say anything about how this permission is used or what it even really means to grant this access permission.

It would be nice if this were explained so I can understand the risks associated with granting such invasive permissions to the Projects app.

https://autark.gitbook.io/open-enterprise/apps/projects

![Screenshot_2019-11-02 Build software better, together](https://user-images.githubusercontent.com/9424721/68079137-e1781b00-fdba-11e9-940d-e567ef7210b2.png)

**Comment by stellarmagnet** [comment]
@chadoh do we need access to all of this?

**Comment by chadoh** [comment]
I discussed this with @john-light a bit in Keybase, and he pointed out that this new approach still doesn't answer some questions that someone might have before granting us initial permissions. Namely, we still do not explain:

> how the permissions are actually used, what "granting permission" to this app actually means, etc. Like, if I grant permission to this app, does it mean _someone at Autark_ could do all these things with my account? Where are the access tokens stored? etc

Answering these questions more fully will only help people trust us more: we do not store these access tokens anywhere that's available to the Autark team, only in the user's local browser. John points out:

> this seems like an important detail that should definitely be communicated at the very beginning of the permission authentication flow, because this is different than pretty much any other OAuth use-case where users are authorizing some centralized third-party app (and by extension, the developers of that app) to have all these permissions to do things with their account. In this case, the granting of permission doesn't actually provide any third-party authority to do anything with the user's account; the user (via their local browser token) is the only person who can access their GitHub account via the Projects app.

Given all of this, John proposes that when we first request GitHub access, we display a message saying something like:

> `(Granting this permission does not give any third party access to your GitHub account. Read [here] for more details.)` where "here" is a link to more documentation about how decentralized apps are awesome and respect user privacy/security and the token is only stored locally in the user's own browser and not accessible by any third parties [such as Autark employees].

An important caveat: OAuth handshakes do require one centralized component: the piece of the system where private keys identifying Autark are stored, which is the piece of the system that relays a user's token back to their browser. We use a simple app that does not log or retain tokens, but even having this centralized piece creates the possibility of our server being compromised, in which case user's tokens could be stored or copied to an attacker's server. 

John continues:

> Out of an abundance of caution, due to this potential attack vector, it may still make sense then to implement your incremental permissioning approach [implemented in this Pull Request]. This way, in case the worst case does happen, the damage can be minimized.
> 
> I do think it's worth explaining what is happening here in depth 1) because transparency around what kind of risks user data is being exposed to is good in general and 2) this is different than just about every other part of the Aragon experience, which doesn't rely on third parties protecting secrets.
>
> It could be fully explained in the "more details" link, I think the copy string I suggest above is still accurate enough since the intention and usual/best case scenario is that no third party has access to the GitHub account once the permission is granted.

I agree with all of John's sentiments, but I lack the design imagination to figure out where to put the initial suggested message. Any ideas, @stellarmagnet @jayalaves? 

Also, @jayalaves, do you feel confident writing the more in-depth security explanation in our user guide?

**Comment by stellarmagnet** [comment]
@chadoh thanks for digging deep on this. I totally agree with John's sentiments... will think about this more with @jayalaves and will have the design suggestion soon.

**Comment by stellarmagnet** [comment]
@chadoh can we put a message inside where the Github OAuth code is, or we have to put it in the Projects app (e.g. first screen of the New Project panel?)

**Comment by chadoh** [comment]
Great question, @stellarmagnet. Unfortunately, [I don’t see a way](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/) to put it in the GitHub screen. I think we have to put it in our app itself.

**Comment by stellarmagnet** [comment]
@chadoh @john-light @jayalaves - thoughts on this? [I wrote up some docs](https://autark.gitbook.io/open-enterprise/apps/projects#github-authorization), it's linked below too.

# Change the empty card UI to have purple help icon:
![image](https://user-images.githubusercontent.com/2584493/68259364-87f83200-ffee-11e9-8488-9ff73cdd7980.png)

When you click on the purple icon, you have more details there.... (read on)

## Text inside purple help icon
The Projects app requires you to sign in with GitHub, as the bounty and issue curation system is tied to GitHub issues. Granting this permission does not give any third party access to your GitHub account. <a href="https://autark.gitbook.io/open-enterprise/apps/projects#github-authorization">Read here</a> for more details.


## Text for New Issue panel

The Projects app can make GitHub issues on your behalf, but to do that you need to increase the level of authorization granted to the app. 

If you’re ready to start using the Projects app to make issues, the minimal set of permissions needs to be authorized. GitHub calls this the “<a href="https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes"><code>public_repo</code> scope</a>”.

Granting this permission does not give any third party access to your GitHub account. <a href="https://autark.gitbook.io/open-enterprise/apps/projects#github-authorization”>Read here</a> for more details. 
>

**Comment by john-light** [comment]
@stellarmagnet thanks! the mockup lgtm. I would remove this sentence in your docs:

> This API token is never accessible by anyone, such as Autark employees.

Since it is later contradicted by the sentence that says:

> These authorizations require one centralized component that is managed by Autark: the piece of the system where private keys identifying Autark are stored, which is the piece of the system that relays your API token from GitHub back to your browser. 

So there is a moment, however brief, during which the API token _is_ accessible to Autark employees. However, I think this is explained well enough. And so removing the first sentence quoted above makes the whole section accurate and helpful as far as explanations go, imho.

**Comment by chadoh** [comment]
@stellarmagnet do we also want to mention, in the help text, that GitHub is only the _first_ of many planned ways to use the Projects app?

**Comment by ottodevs** [comment]
> @stellarmagnet thanks! the mockup lgtm. I would remove this sentence in your docs:
> 
> > This API token is never accessible by anyone, such as Autark employees.
> 
> Since it is later contradicted by the sentence that says:
> 
> > These authorizations require one centralized component that is managed by Autark: the piece of the system where private keys identifying Autark are stored, which is the piece of the system that relays your API token from GitHub back to your browser.
> 
> So there is a moment, however brief, during which the API token _is_ accessible to Autark employees. However, I think this is explained well enough. And so removing the first sentence quoted above makes the whole section accurate and helpful as far as explanations go, imho.

The information that @chadoh provided is incorrect, there is no moment where the API token is accesssible to Autark employees, the centralized server we use is part of the oauth protocol and provides a handshake between github and our app, consisting in the exchange of internal `client_secret` that Github provides to Autark, combined with a temporal `auth_code`, that once they are validated to check the origin of the request, it will result into the user receiving being redirected to the Projects app and the final Token being stored into the user browser.

**Comment by chadoh** [comment]
@ottodevs gatekeeper [receives the `token` from GitHub](https://github.com/prose/gatekeeper/blob/development/server.js#L36) and passes it [back to the user's browser](https://github.com/AutarkLabs/open-enterprise/blob/e9e1edb3b79f60deffca061476226e3701bb0856/apps/projects/app/App.js#L74). 

We are running gatekeeper on our server. That means that the user's token is, briefly, on the server. Just like any other server that does such an OAuth handshake, if the server were compromised, these tokens could be obtained by an attacker.
