### ISSUE TITLE
Add disclaimer to Address Book

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1538]
Add a disclaimer that is at the top of the Address Book app. This is temporary until our dependency PR is merged.

See Figma: https://www.figma.com/file/GEilkBpZ6cl10pPSnLMeDuZb/Address-Book?node-id=359%3A1481
* Hyperlink should open new window here: https://github.com/aragon/aragon.js/pull/391
* Display this disclaimer only on the Empty page

**Comment by jayalaves** [comment]
Added disclaimer message, the same as we have in our guide, referencing the PR for now until we have the app thread on the forum (which I will do once the details.md text can be used for that purpose too). Here's the [reference link on Figma](https://www.figma.com/file/GEilkBpZ6cl10pPSnLMeDuZb/Address-Book?node-id=359%3A1481).
