### ISSUE TITLE
Add borders around our screenshots in the docs

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1546]
We should add borders around our screenshots in the docs. We should adapt a similar border style / color as the Aragon.org Help Scout docs:
* https://help.aragon.org/article/19-voting

**Comment by stellarmagnet** [comment]
We should probably use css instead of doing it directly on the image.

Maybe @PeterMPhillips can help? I just invited him to the Gitbook.

https://gitbookio.gitbooks.io/documentation/styling/book.html

**Comment by jayalaves** [comment]
Borders now live across all images on our [documentation](https://autark.gitbook.io/open-enterprise/) 👍
