### ISSUE TITLE
Validation being displayed before entering a frequency

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1554]
Previously, this validation error showed up once you entered a number for the frequency. Right now, it shows up as soon as you select "recurring dividend" and have a blank frequency.

![image](https://user-images.githubusercontent.com/2584493/68368919-ece68180-00ed-11ea-9372-97ef33d85a18.png)

Additionally, sometimes we get this:

![image](https://user-images.githubusercontent.com/2584493/68369388-09cf8480-00ef-11ea-8788-849317fcf44c.png)

--
We didn't fully think through this possible edge case. My new proposal is to do as follows:

1. Get rid of this warning message / warning icon.

2. Have the blue message, that is conditionally displayed (if at least 1 disbursement exists):

if 2+ disbursements:
> The first reward under this policy will be disbursed 1 month after your chosen start date, and repeat every 1 month until your chosen end date. Dates are approximate as our disbursements occur based on block number.

If 1 disbursement:
> There will only be a single reward under this policy, which will be disbursed 1 month after your chosen start date. Dates are approximate as our disbursements occur based on block number.

**Comment by jayalaves** [comment]
Based your suggestion, then we'd simply have no warning message at all if the configuration doesn't output a disbursement date? (I guess the user would realize once in the review panel anyway and go back to editing the reward before submitting)

**Comment by stellarmagnet** [comment]
No, we actually need an error message if there are 0 disbursements in the range.

Right now, this is actually incorrect, since the disbursement doesn't occur on the first date:
![image](https://user-images.githubusercontent.com/2584493/68372558-fa076e80-00f5-11ea-92d0-c8105f83656f.png)

Do you have a suggestion for the error message? I thought we had something before...

**Comment by stellarmagnet** [comment]
@e18r 

For 0 disbursements due to the date range (and start date is a valid start date), show a red x, and the following error:

> Based on your selected parameters, there will be no disbursements, as your end date falls before the end of the first cycle. Please choose an end date that is at least 1 month after the start date.

And to repeat the other requirements...

For 2 disbursements, show blue info box:

> The first reward under this policy will be disbursed 1 month after your chosen start date, and repeat every 1 month until your chosen end date. Dates are approximate as our disbursements occur based on block number.

For 1 disbursement, show blue info box:

> There will only be a single reward under this policy, which will be disbursed 1 month after your chosen start date. Dates are approximate as our disbursements occur based on block number.


--- in the above 1 month can be 2 months, 1 week, 2 days, etc...
