### ISSUE TITLE
Allocation dot vote got rejected for unclear reasons

### ISSUE THREAD

**Issue by jayalaves** [AutarkLabs/open-enterprise#1556]
**Describe the bug**
My dot vote got rejected after voting, and I'm not sure what the reason is.

**Mainnet or testnet?**
Rinkeby

**Organization**
http://rinkeby.aragon.org/#/nov5oetest/

**To Reproduce**
See the moment where the vote got rejected [here](https://www.youtube.com/watch?v=RqUKq8-qrF4&feature=youtu.be&t=2107), and the whole process beforehand to reproduce is available a few minutes earlier in the video.

**Expected behavior**
I presume that the allocation dot vote should've taken in my vote results and be ready to be enacted once the time was over.

**Desktop (please complete the following information):**
 - OS and OS version: macOS Catalina 10.15
 - Browser and browser version: Google Chrome 78.0.3904.87 (Official Build) (64-bit)

**Comment by stellarmagnet** [comment]
Watch closely in the video -- you will see that the Dot Vote closed before your voting transaction got processed.

**Comment by jayalaves** [comment]
🤦
