### ISSUE TITLE
Updates to bounty context menu and fund issues panel

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1571]
1. We don't have the "update funding" plumbing fully working; let's *remove* this feature from the bounty context menus

2. Update the other actions to be in *sentence case*:
* Submit application
* Review application
* Fund issue

3. Fund issues panel: If selecting multiple issues and ones have funding, display the following message.
> The following issues already have active bounties, so they have been discarded from this funding proposal:
... (list of issues)

**Comment by javieralaves** [comment]
@PeterMPhillips  Running into an issue trying to open a work submission whereby clicking on 'View work submission' from the context menu or from the bounty widget renders a blank screen.

**Comment by javieralaves** [comment]
Reviewed this in the continuous deploy on December 19, 2019. Works as expected!
