### ISSUE TITLE
Provide support for open submission bounties

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1572]
* As a project manager, I should be able to create funding proposals where applications are not required to be able to submit work.
* As a bounty hunter, I should be able to submit work to bounties without needing to first submit an application.

**Comment by Quazia** [comment]
The scope of this ticket may shift once we have designs.

**Comment by jayalaves** [comment]
Designs available here:

- [Settings tab](https://www.figma.com/file/Xnn4lQJX4d5AautuvmAlnxHf/Projects?node-id=1138%3A19436) should now display a "Funding process" label
- [Issues that've been funded under open submissions](https://www.figma.com/file/Xnn4lQJX4d5AautuvmAlnxHf/Projects?node-id=1138%3A20212) should directly ask for work

I suppose that it'd be possible for more than one person at a time to submit work under this open submission funding process, correct? If so, we should re-use some of the patterns I've already designed for the other funding process, in terms of displaying "x work submitted" with the "view work" button [for the person that submitted](https://www.figma.com/file/Xnn4lQJX4d5AautuvmAlnxHf/Projects?node-id=389%3A7098), and an "submit work" and "review work" buttons [for other members](https://www.figma.com/file/Xnn4lQJX4d5AautuvmAlnxHf/Projects?node-id=1119%3A18453).

**Comment by stellarmagnet** [comment]
@jayalaves per our discussion yesterday, we cannot make the Settings tab change as of now. Can this dropdown be added to the top of the Fund Issues panel?

> I suppose that it'd be possible for more than one person at a time to submit work under this open submission funding process, correct?

Yes, this would be possible. So are we going to make updating the status panel a dependency to complete this ticket? If you can connect the tickets and ensure the requirements are clear, that would help.

**Comment by stellarmagnet** [comment]
@jayalaves let me know if you have permission to update the original description of this ticket, we should document the specs & designs there.

**Comment by stellarmagnet** [comment]
Closing this ticket as we are reorganizing Zenhub for product. It will be covered: https://github.com/AutarkLabs/product/issues/4
