### ISSUE TITLE
Improve the style of the budget card

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1573]
* Fix the location of the bar so they are always at the same location on all budget cards, regardless of the length of the budget name
* Change the location of the "per period"
* Increase the width of the utilization bar
* Add margin around budget cards on narrow screens (see #1702 for screenshots)

Design:

[See Figma frame D 1.0 for latest](https://www.figma.com/file/9c4GAhAa1LhH1TmJC8vCHA/Allocations?node-id=964%3A27)

![screenshot](https://images.zenhubusercontent.com/5699129a638e718c99601ac2/cbd242d8-bcc2-4123-9902-bc43b914d7c8)

**Comment by jayalaves** [comment]
Just updated the design, you can find the latest version [available here](https://www.figma.com/file/9c4GAhAa1LhH1TmJC8vCHA/Allocations?node-id=192%3A2032).

**Comment by jayalaves** [comment]
Design available in the Figma master branch [here](https://www.figma.com/file/9c4GAhAa1LhH1TmJC8vCHA/Allocations?node-id=878%3A20278).

**Comment by javieralaves** [comment]
Looking good!

**Comment by javieralaves** [comment]
Tested this in the continuous deploy from December 17th, 2019.

✅ Looks as expected.
