### ISSUE TITLE
Reevaluate the "New budget" action

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1574]
It's not intuitive how to create an allocation from the Allocations app.

Let's reevaluate where the "New budget" action should be.

**Comment by jayalaves** [comment]
@stellarmagnet [Here's an initial design brainstorm](https://www.figma.com/file/9c4GAhAa1LhH1TmJC8vCHA/Allocations?node-id=858%3A7405) I've made. Please review my comments there as well, noting some limitations for some of those alternatives. Let me know what you think!

**Comment by jayalaves** [comment]
We've reviewed this during our last call and a new issue with a solution has been created.
