### ISSUE TITLE
Implement budget detail page

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1575]
Whenever you click on a budget card, you should be able to view the details of the budget and it's allocation history.

WIP design:
https://www.figma.com/file/9c4GAhAa1LhH1TmJC8vCHA/Allocations?node-id=798%3A6377

**Comment by jayalaves** [comment]
Latest iteration of the design available in the master branch [here](https://www.figma.com/file/9c4GAhAa1LhH1TmJC8vCHA/Allocations?node-id=878%3A19026).

**Comment by javieralaves** [comment]
Tested this on the continuous deploy from December 17th 2019. 

✅ Looks great!
