### ISSUE TITLE
Make the actions button look more disabled when it's disabled

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1581]
It shouldn't be clickable etc.

![image](https://user-images.githubusercontent.com/2584493/68432916-38d70c00-016a-11ea-8e41-5198451e4214.png)

**Comment by jayalaves** [comment]
We should remove this button unless it's clickable, right? @stellarmagnet @rkzel

**Comment by stellarmagnet** [comment]
What do you mean? I think buttons should always be displayed, just disabled

**Comment by chadoh** [comment]
@rkzel taking care of this as part of #1463.

@stellarmagnet per discussion in our #design channel, I believe Radek is going to remove the button entirely until some issues have been selected.
