### ISSUE TITLE
Data retained after going from Edit Budget to New Budget

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1584]
1. Navigate to allocations app that has budgets
2. Click on a budget card and click "edit budget"
3. Close/cancel
4. Click on "New budget"

You'll see the data from the budget you edited there. 

Expected: when I hit new budget, the fields should be empty

**Comment by javieralaves** [comment]
Tested this in the continuous deploy from December 17th, 2019.

✅ This issue no longer exists.
