### ISSUE TITLE
Show rejected Allocations in Allocations app

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1586]
In the allocations app, we are only showing approved allocations.

We should display all of them there.

**Comment by Quazia** [comment]
The rejected allocations arn't really stored anywhere right now. We could potentially try and use the forwarder API somehow to handle this, but even then I think this requires more research.

**Comment by javieralaves** [comment]
Closing this as it's more comprehensively addressed in #1852, including pending allocations.
