### ISSUE TITLE
Improve the rewards tables

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1587]
* improve the status terms / icons
* improve the display of past rewards
* improve the order
* Show block number of next payout

Needs design

**Comment by jayalaves** [comment]
Made some updates in the [Rewards exploration branch](https://www.figma.com/file/23c7bPgSZpY5lgQR6PmHsA/Rewards?node-id=90%3A0).

- Block number displayed across views
- Improved status terms and information display
- Added an additional view "View my reward" with status information
- Context menus depending on my reward status

**Comment by e18r** [comment]
I will transform this into an epic.

**Comment by e18r** [comment]
I created issues for each task on this epic. @jayalaves can you please check if anything is missing?
