### ISSUE TITLE
Provide support for editing budgets

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1588]
To implement this feature, the following is required:
* Update the currency box so the proper currency is displayed when editing (test when 3+ currencies in vault) - #1596 
* Improve the radspec - currently it's not working bc it's trying to render the token symbol, and we don't have it.

(Note: the current feature had to be commented out from the dropdown, since it was incomplete).

**Comment by javieralaves** [comment]
Tested this in the continuous deploy from December 17th, 2019.

✅ Everything works as expected!
