### ISSUE TITLE
Submit application shouldn't be displayed for past-due bounties

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1590]
![image](https://user-images.githubusercontent.com/2584493/68444796-ce839300-018c-11ea-8e18-55230cc740ab.png)

**Comment by stellarmagnet** [comment]
Closing this issue, as it will be covered as acceptance criteria for this epic: https://github.com/AutarkLabs/product/issues/4

**Comment by PeterMPhillips** [comment]
This issue was completed with this merge: https://github.com/AutarkLabs/open-enterprise/pull/1674
