### ISSUE TITLE
Funding several issues including one with funding behaves poorly

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#1591]
**Describe the bug**

When selecting multiple issues, one with funding several things occur.
Below, only the issue with funding should be displayed in the warning message.
![paste (3)](https://user-images.githubusercontent.com/6549550/68444582-4493f400-01a5-11ea-86d9-9172c10864f3.png)
Additionally, the sentence "To update an individual..." should be removed.

Eventually, when submitting the transaction, it fails with the following error.
![paste (2)](https://user-images.githubusercontent.com/6549550/68444534-2201db00-01a5-11ea-9b7d-05f91e19ebe2.png)

**To Reproduce**

1. Fund one issue with a bounty
2. Select multiple issues, 2 without a bounty and 1 with a bounty.
3. Select "fund issues"
4. This will bring you to the panel above, showing it the issues

**Comment by javieralaves** [comment]
Tested this in the continuous deploy from December 17th, 2019. Works as expected!
