### ISSUE TITLE
Context menu for fulfilled bounties doesn't have anything in it

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1592]
Should be able to still review past applicants and past work
Right now the context menymenu doesnt have anything available in it

![image](https://user-images.githubusercontent.com/2584493/68444981-6da88a80-018d-11ea-8194-ab275fcbb79e.png)

**Comment by jayalaves** [comment]
This should display "View work", as in the work that marked the bounty as completed.

**Comment by stellarmagnet** [comment]
Closing this ticket, it's covered in our new bounty experience epic.
