### ISSUE TITLE
Recognize DAI as a valid token in our dropdowns

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1595]
The following dropdowns / apps aren't recognizing mainnet DAI:

* Projects - Fund issues panel (fixed funding)
* Projects - Settings - Hourly funding
* Rewards - New reward - Amount field

Additionally, whenever the finance app has *only DAI*, and you try to fund issues, the "No funds found" UI is displayed.

![image](https://user-images.githubusercontent.com/2584493/68451610-4ad5a080-01a4-11ea-83b3-bd900c4d8315.png)

![image](https://user-images.githubusercontent.com/2584493/68451632-5628cc00-01a4-11ea-84c9-603319e24880.png)

![image](https://user-images.githubusercontent.com/2584493/68451642-5d4fda00-01a4-11ea-862a-b2919e0ec680.png)

**Comment by topocount** [comment]
@stellarmagnet what dao is this example from?

**Comment by stellarmagnet** [comment]
@topocount https://mainnet.aragon.org/#/mydaodao/

**Comment by javieralaves** [comment]
Testing this on the [My DAO DAO](https://mainnet.aragon.org/#/mydaodao/) on December 19th, 2019. The issue seems to be fixed.
