### ISSUE TITLE
When editing a budget and you have 3+ items in dropdown...

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1596]
When editing a budget and you have 3+ items in dropdown, and your budget is set to the 3rd token, it shows up as the 2nd token when editing a budget. This is because this line is assuming that the dropdown only has 2 options, and if the budget is not ETH, it is the 2nd token. (Note: budget editing has been disabled for now, bc of this current limitation, although #1588 is also needed before we can provide support)

https://github.com/AutarkLabs/open-enterprise/blob/b244fe76ab679b1f943e46e0d13914fede4b037d/apps/allocations/app/components/Panel/NewBudget.js#L49

**Comment by javieralaves** [comment]
Tested this in the continuous deploy from December 17th, 2019.

✅ Everything works as expected.
