### ISSUE TITLE
Unexpected weird date flickering

### ISSUE THREAD

**Issue by javieralaves** [AutarkLabs/open-enterprise#1612]
### Description

I created a recurring reward, set in the past, that rewards once a day for an entire week, and moving between tabs the dates flicker and I'm not sure they're displaying the right information.

### Expected behavior

"Next payout" should always be the nearest present day for a reward to be disbursing an amount, and in "my rewards" new disbursement should be the earliest date of that reward that I have to claim. (@stellarmagnet thoughts?)

### Screenshots

[See video here](https://www.notion.so/autark/Unexpected-weird-date-flickering-2072232bfee64c769779e11e7d9e8c15), how the flickering happens when I switch tabs.

**Comment by jayalaves** [comment]
Link: https://rinkeby.aragon.org/#/nov5oetest/0x1e40f451be28321f800e283e52d9ab0c5a94153a/
Steps to reproduce:
- Create a recurring dividend that's set a few days before today and disburses once a day for 7 days
- Once enacted, click between tabs in the app and you'll notice some syncing issues in dates. I spotted them as shown in the video in the disbursement date column in the first tab, and in the next payout column in the second tab

**Comment by javieralaves** [comment]
Closing this since it's been hard to reproduce and identify. Will reopen this issue if the problem reappears.

**Comment by ottodevs** [comment]
> Closing this since it's been hard to reproduce and identify. Will reopen this issue if the problem reappears.

It was easily reproducible, and we located the exact place in the code where this was happening.

@e18r and me had a session 2 weeks ago to investigate on this, and we arrived to the conclusion that it was caused by the way the claiming dates are re-calculated on each tab change, I hope Emilio worked into some workaround.
