### ISSUE TITLE
"Next payout" displays dates in the past

### ISSUE THREAD

**Issue by javieralaves** [AutarkLabs/open-enterprise#1614]
### Description

Reward that started in a past date has "next payout" displayed also in a date in the past.

### Expected behavior

No matter whether the reward was started in a past date or not, "next payout" should always be an upcoming date, even if you have rewards pending to collect from past dates. Screenshot below was taken on Fri Nov 8 2019.

### Screenshot

<img width="1440" alt="Screenshot_2019-11-08_at_14 07 34" src="https://user-images.githubusercontent.com/28843778/68661447-3fcf9700-053b-11ea-8e8d-4791094f3fe6.png">

**Comment by stellarmagnet** [comment]
@javieralaves-- i'm not seeing a design for what this should look like for one-time rewards or recurring rewards that ended?

**Comment by Quazia** [comment]
This will require a slight logic re-work but shouldn't be anything overly complex. All of the state needed should be available. If work on this begins and it doesn't seem fairly obvious how to handle this within the first ~30 minutes let me know so I can give it a look.

**Comment by javieralaves** [comment]
There's not necessarily a need for an additional design, simply to account for the change in logic on how "Next payout" should work. Other than that, once there are no more payouts we could display "Completed".

**Comment by stellarmagnet** [comment]
@javieralaves then the user will lose context for when the reward was scheduled for

**Comment by javieralaves** [comment]
@stellarmagnet You can still find that information available in the ['View reward' panel](https://www.figma.com/file/23c7bPgSZpY5lgQR6PmHsA/Rewards?node-id=454%3A8961) from the context menu, right?

**Comment by stellarmagnet** [comment]
I guess it's "safe enough to try" with this suggestion.

**Comment by e18r** [comment]
@javieralaves The screenshot you took is from a one-time dividend that took place in the past. There are no upcoming dates in that case, so the "next payout" field correctly displays a date in the past. Please let me know if that behavior should change.

You probably were referring to a recurring dividend with dates still in the future. Please make sure that in that case, dates are not displayed correctly. Otherwise it might make sense to just close or rephrase this ticket.

**Comment by javieralaves** [comment]
@e18r Essentially, the ‘All rewards’ table should not display a next payout if that disbursement is in the past. We will instead reflect ‘Completed’ to show that there are no next payouts.
