### ISSUE TITLE
Labels in "new reward" panel have old styling

### ISSUE THREAD

**Issue by javieralaves** [AutarkLabs/open-enterprise#1615]
### Description

Labels in "New reward" panel have the old style.

### Expected behavior

Update to new style.

### Screenshot

<img width="1440" alt="Screenshot_2019-11-08_at_14 02 03" src="https://user-images.githubusercontent.com/28843778/68661558-70afcc00-053b-11ea-9ade-c21be93ad863.png">

**Comment by e18r** [comment]
@javieralaves if you wanna make me feel happy, specify whether the screenshot corresponds to the "current" or to the "expected" state (I figured it's the current state). And if you wanna make me feel ecstatic, include both states :)

**Comment by e18r** [comment]
@javieralaves after further inspection, it seems to me that the labels in the New Reward panel are already using the new styling by means of AragonUI's `<Field>` component.
![Screenshot from 2019-12-09 14-11-24](https://user-images.githubusercontent.com/16065447/70465018-0a608f80-1a8e-11ea-8129-21fb7e3ea360.png)

The image you uploaded seems not to correspond to the latest dev. Here's how it looks on my machine:
![Screenshot from 2019-12-09 14-14-35](https://user-images.githubusercontent.com/16065447/70465248-8d81e580-1a8e-11ea-8f92-cea3eaf817bd.png)

**Comment by javieralaves** [comment]
Fantastic, we’ve got this one covered then! :) thanks for double checking @e18r!
