### ISSUE TITLE
Fix text styling in buttons and panel titles

### ISSUE THREAD

**Issue by javieralaves** [AutarkLabs/open-enterprise#1619]
### Description

Some buttons and panel titles have a mismatch styling with the rest of buttons and panels from Aragon One apps.

### Expected behavior

Title case only the first word of each panel and button, the rest stay lowercase.

### Cases
May be missing a few cases, but these are the ones I've recognized:

**Address Book**
- [ ] "New entity" panel title and button
- [ ] Global "New entity" button

**Allocations**
- [ ] "New allocation" from context menu

**Dot Voting**
- [ ] "Execute vote" button
- [ ] "Submit vote" button

**Projects**
- [ ] Global "New project" button
- [ ] "New project" panel title
- [ ] Global "New issue" button
- [ ] "New issue" panel title
- [ ] "Submit issue" in New issue panel title
- [ ] "Remove project" from context menu
- [ ] "Fund issue" from context menu (and all the other context menu options across bounty phases)
- [ ] "Curate issues" from actions button
- [ ] "Save changes" button in settings tab

**Rewards**
- [ ] Global "New reward" button
- [ ] New reward panel title

**Comment by rkzel** [comment]
This got done in PR #1682
