### ISSUE TITLE
Projects/Submit Application: action shouldn't be available when user already submitted

### ISSUE THREAD

**Issue by PhilH** [AutarkLabs/open-enterprise#1622]
**UX Improvement**
When a user already submitted an application, the option of submitting again (via the action menu in the issue list, or the button in the issue page) is still available. The user can fill the submission data and send the request. Only then the request is turned, with the infamous "Action impossible" panel. If it's possible to catch it earlier, it would be much better to deactivate or hide these options.

**Comment by jayalaves** [comment]
@PhilH Thank you 🙏 for your feedback. We'll be tackling this UX improvement by enhancing the status information #1648 to make sure individuals have more conditionally rendered data based on their engagement history with a bounty.

**Comment by javieralaves** [comment]
This is being addressed in an upcoming update!
