### ISSUE TITLE
Projects/Review applications: multiple applications are difficult to spot

### ISSUE THREAD

**Issue by PhilH** [AutarkLabs/open-enterprise#1623]
**UX Improvement**
When multiple applications are submitted, the reviewer can hardly see them since there is practically no difference between a single vs. multipls applications for the same issue:
- the "Review applications" button displays "applications" in a plural form whether or not there is more than one application
- the "Review application" panel is exactly the same whether or not there is more than one application (and in both cases, its title is in singular form)
- the only difference is in the action menu of the issue list, where the number of submissions is displayed on the right on the action, but the menu has to be opened ("Review application (2)")

See below screenshots showing both cases: issue with one submission vs an issue with two submissions

I took me some time to realize where was the second one. At the minimum, I suggest to use a list rather than a drop-down list so that existing submissions are easier to spot.

Only one submission:
![image](https://user-images.githubusercontent.com/53337/68681042-f2ffb680-0562-11ea-9028-ca823aaa98e3.png)

Two submissions:
![image](https://user-images.githubusercontent.com/53337/68681073-001ca580-0563-11ea-86a7-c10298ccc2f8.png)

**Comment by jayalaves** [comment]
Hey @PhilH, we'll be enhancing the status information displayed, including a count for the number of applications received per bounty as shown below:

<img width="1440" alt="D 3 2 2 - Application Received – Reviewer View" src="https://user-images.githubusercontent.com/28843778/68931681-54a56800-0791-11ea-9bcc-4b6a0baa96ef.png">

We'll also be updating the button text to plural when appropriate. I hope both of these enhancements remedy some of the confusion you've pointed out in this issue. I'm open to any further feedback! 🙂

**Comment by PhilH** [comment]
Sounds much better, let's see with real users! ;)
Thanks for the feedback

**Comment by javieralaves** [comment]
This is being addressed in an upcoming update :)
