### ISSUE TITLE
Projects/Review applications: minor issue with the applicant drop-down list

### ISSUE THREAD

**Issue by PhilH** [AutarkLabs/open-enterprise#1624]
**UX Improvement**
When switching to another applicant in the "Review application" panel, the content of the application is correct, but the list box automatically switches back to the first element of the list. As a result, the currently selected element doesn't match the rest of the content of the panel. See example in the screenshot below.

Issue br2, content submitted by test-aut-ef, selected applicant is test-aut-ef
![image](https://user-images.githubusercontent.com/53337/68681503-cef0a500-0563-11ea-8fc8-c8981d13c79d.png)

Issue br2, content submitted by PhilH, selected applicant switched back to test-aut-ef
![image](https://user-images.githubusercontent.com/53337/68681551-dd3ec100-0563-11ea-93fe-68e4420beb3e.png)

**Comment by javieralaves** [comment]
We'll be introducing some new changes to the Projects app that makes this experience a lot smoother!
