### ISSUE TITLE
Projects/Curate issues: mandatory "description" field can be submitted as an empty field

### ISSUE THREAD

**Issue by PhilH** [AutarkLabs/open-enterprise#1630]
**Describe the bug**
In the "Curate issues" panel, "Description *" field is supposed to be mandatory, but there's no validation and it can be submitted without value.

**Mainnet or testnet?**
Rinkeby

**Organization**
oetest4

**To Reproduce**
1. Go to Projects
2. Select multiple issues
3. Select "Curate issues" in the action menu
4. Click on "Submit curation" button without filling the mandatory field "description"
5. The submission is accepted

**Expected behavior**
Set the field as optional (remove the star sign) or check that the user typed some value.

**Screenshots**
![image](https://user-images.githubusercontent.com/53337/68687657-d5841a00-056d-11ea-9c33-c513818eb89c.png)

**Desktop (please complete the following information):**
- OSX 10.13
- Brave

**Comment by javieralaves** [comment]
Covered in our upcoming update!
