### ISSUE TITLE
Integrate filters bar and new buttons set up

### ISSUE THREAD

**Issue by javieralaves** [AutarkLabs/open-enterprise#1642]
As shown [in frame D 1.0 – Main here](https://www.figma.com/file/9c4GAhAa1LhH1TmJC8vCHA/Allocations?node-id=878%3A20278).

![screenshot](https://images.zenhubusercontent.com/5699129a638e718c99601ac2/c48af4ab-8981-4da3-ad5e-7d32ea97c77b)

**Comment by javieralaves** [comment]
Testing this on the continuous deploy from December 17th 2019.

✅ Filters work as expected
✅ Buttons are placed as expected
❌ Screen goes blank when I click on 'New allocation'

Waiting for a fix on the 'New allocation' button in order to mark this one off. @chadoh @e18r please let me know when changes have been merged to re-review this issue.

**Comment by javieralaves** [comment]
@chadoh Were you able to merge a fix for this?

**Comment by chadoh** [comment]
@javieralaves yes! Fixed by #1794, and it looks like Travis successfully deployed since then.

**Comment by javieralaves** [comment]
Reviewing this in the continuous deploy [Neudune DAO](https://rinkeby.aragon.org/#/neudune/0x66cad2ce53968d08461cfb0b71568d66f2985d4f/) on December 20th, 2019. Looks good!
