### ISSUE TITLE
Add line about period info in "New budget" panel

### ISSUE THREAD

**Issue by javieralaves** [AutarkLabs/open-enterprise#1643]
As shown [here](https://www.figma.com/file/9c4GAhAa1LhH1TmJC8vCHA/Allocations?node-id=878%3A20417).

![D 0 2 - New Budget](https://user-images.githubusercontent.com/28843778/68867105-98e32a80-06f5-11ea-9240-6b9dfeb65be1.jpg)

**Comment by chadoh** [comment]
Incorporated in #1641
