### ISSUE TITLE
Allocation/New budget: upon creation, budget is set to zero for an unknown reason

### ISSUE THREAD

**Issue by PhilH** [AutarkLabs/open-enterprise#1646]
**Describe the bug**
I tried to set a budget using an ECR20 token (EF2), whose contract address is:
0xb23d5c1d53c70e59eb863e409923577eb42f809b
Once created, the budget has a value of zero, even though a non-zero value was submitted.

**Mainnet or testnet?**
Rinkeby

**Organization**
oetest3, efdaotest03

**To Reproduce**
Assuming you have some EF2 tokens (I can send some to you):
1. Deposit EF2 via the Finance app
2. Go to Allocation
3. Click on New budget
4. Select EF2 and type a number of tokens
5. Create the transaction
6. See the result: the budget is 0 EF2 (see screenshots)

**Expected behavior**
The budget should show the value submitted by the user

**Screenshots**
![image](https://user-images.githubusercontent.com/53337/68894385-81bd3080-0727-11ea-8bf0-131956704f4c.png)

![image](https://user-images.githubusercontent.com/53337/68894411-8d105c00-0727-11ea-9f04-c3eaa2336a5c.png)

**Desktop (please complete the following information):**
 - OSX 10.13
 - Chrome + Metamask

**Comment by e18r** [comment]
@PhilH I was able to reproduce the bug on your Rinkeby DAO. Can you provide more details about this EF2 token? How did you create it? Is it any different from other ERC-20 tokens you created that work well? Thank you.

**Comment by PhilH** [comment]
AFAIK it's a standard ERC20, we were working on another test on Aragon with a friend who set up the contract so that we can play with it on our tests. I haven't tested other ERC20 tokens on Aragon, apart from the Aragon org native tokens (actually I don't know if they are standard ERC-20).

**Comment by Quazia** [comment]
Yeah if you have the contract of the token causing the issues that would be super helpful.

**Comment by e18r** [comment]
@PhilH I tried to reproduce this on my development environment with a custom ERC-20 token, but I was unable to. It would seem to me that this behavior is specific to the way your ERC-20 token was created, and thus, as @Quazia says, I need its contract code in order to dig any further.

**Comment by e18r** [comment]
With @PhilH's help, I was able to reproduce this on my local environment by using the following contract:

    pragma solidity ^0.5.11;

    import "@openzeppelin/contracts/token/ERC20/ERC20Burnable.sol";
    import "@openzeppelin/contracts/token/ERC20/ERC20Detailed.sol";
    import "@openzeppelin/contracts/token/ERC20/ERC20Mintable.sol";

    contract EFToken is ERC20Burnable, ERC20Detailed, ERC20Mintable {

      constructor()
      public
      ERC20Detailed("EF2", "EF2", 8)
      {
          _mint(0xb4124cEB3451635DAcedd11767f004d8a28c6eE7, 1200000000);
      }

    }
