### ISSUE TITLE
DAI to SAI conversion

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#1654]
Make sure that our conversion from SAID to DAI timeline and implementation is in sync with A1.
- [ ] Publish and test this via our continuous deploy apps on mainnet before doing the official mainnet packages.
- [ ] Publish official packages to Rinkeby
- [ ] Publish official packages to Mainnet
- [ ] Document the deploy logs per internal processes

**Comment by javieralaves** [comment]
@Quazia What are the steps to verify that this has been completed?

**Comment by javieralaves** [comment]
Testing this on a [Mainnet DAO](https://mainnet.aragon.org/#/mydaodao/) on December 19th, 2019. Works as expected!
