### ISSUE TITLE
FilterBar: context and mobile version

### ISSUE THREAD

**Issue by rkzel** [AutarkLabs/open-enterprise#1664]
Although mobile version is at this point not considered top priority, preparing it was a good opportunity to redesign how filtering works. Details:

1. Because design for mobiles reaches up to the top app level:

![Screenshot from 2019-11-19 13-35-05.png](https://images.zenhubusercontent.com/5ad4f5d94b5806bc2bcf53cf/d685d70f-582a-41ee-8651-8f782445e914)

it was finally necessary to decouple `Issues` from `FilterBar`. It happened via `IssueFiltersContext`, which contains everything needed to display filters - along with functions to set, remove, clean and display current state of filtering. The context is then used in Issues.

2. Side effect of the change: prop drilling was hugely reduced across Issues and FilterBar (which is the biigest part of the app), for example:

```const FilterBar = ({
  allSelected,
  issuesFiltered,
  handleSelectAll,
  deselectAllIssues,
  selectedIssues,
}) => {
```

vs

```const FilterBar = ({
  allSelected,
  filters,
  bountyIssues,
  issues,
  issuesFiltered,
  handleSelectAll,
  handleFiltering,
  handleSorting,
  setParentFilters,
  disableFilter,
  disableAllFilters,
  deselectAllIssues,
  selectedIssues,
  onSearchChange,
}) => {
```

3. General modernization and simplification of code happened as the second side effect. Logical separation of functionality will improve dev experience and make future development so much easier.

**Comment by javieralaves** [comment]
Closing this as there was nothing merged in then and we'll be addressing this in upcoming issues and epics.
