### ISSUE TITLE
Projects: Simplify Filtering

### ISSUE THREAD

**Issue by chadoh** [AutarkLabs/open-enterprise#1681]
Filtering (and searching in general) is hard; whole companies are built on their ability to make it seem easy. 

After doing technical analysis for #1488 (see [comment](https://github.com/AutarkLabs/open-enterprise/issues/1488#issuecomment-556404941)); feeling overwhelmed; discussing with @Quazia, @jayalaves, and @rkzel; and stepping back; here's what I'm thinking:

1. We want to move on. Filtering is probably not the most important thing for us to focus on, right now.
2. Upcoming changes to Projects, such as supporting Issue Sources other than GitHub, are going to greatly impact the architecture of filtering and searching. This feels like an even stronger argument for "we want to move on" than the last point: much of the work we could do to really polish _current_ Filtering will need to be reworked once we implement new Issues Sources. We save approximately half of that effort if we can somehow skip any further improvements to Filtering for now, and only come back and re-architect it after we have more information about how we want it to work with multiple Issue Sources.
3. If we find some way to somehow skip further improvements to Filtering for now, who knows – maybe we'll find that we like that solution, and that we and our users don't feel a burning need for us to re-implement all the filtering features that our current UI promises but under-delivers.

# Somehow skip further improvements to Filtering for now

How can we do this? What's the minimum viable version of filtering? What can we do that gets us to a _good enough_ filtering solution for now, that won't add endless bug-squashing and re-architecting as we build more important new features?

In my discussions with @jayalaves and @rkzel, we've thought of two possibilities.

## Possibility 1. Minimum Viable Filtering

* Get rid of the Issues tab

  <img width="741" alt="Screen Shot 2019-11-21 at 16 49 42" src="https://user-images.githubusercontent.com/221614/69379745-099ebf80-0c7f-11ea-8910-dac75a198b8d.png">

* Clicking one of the Repositories brings you to a "detail"-style view, which only shows issues from that Repository:

  <img width="724" alt="Screen Shot 2019-11-21 at 16 53 07" src="https://user-images.githubusercontent.com/221614/69380143-d1e44780-0c7f-11ea-97e7-f1045746342a.png">

* As shown in the mockup above, this new version of the Issues page has only a few buttons, positioned to the right in the "Back" bar, with as few filtering/searching/sorting options as we think we can get away with.

**What is the minimally-useful set of filtering/searching/sorting logic?** Great question! I think maybe it's:

* Text search
* Better sorting (see [Part 3 here](https://github.com/AutarkLabs/open-enterprise/issues/1488#issuecomment-556404941))
* **No filtering** – maybe better sorting, with the option to sort by "date funded", is good enough for now.  

Radek disagrees, and thinks maybe we can skip "sort by date funded", and instead keep:

* Filter by Status  

And he could also see an argument for keeping "filter by label." However, I want to really stress something here: **As soon as we have more than one type of filter, we re-open the can of worms we're trying to close.** Many of the technically-challenging, error-prone, eternally-under-rearchitecture considerations I brought up in [Part 2 here](https://github.com/AutarkLabs/open-enterprise/issues/1488#issuecomment-556404941) come right back, as soon as we add more than one filtering option. We can do a great job with one filtering option pretty easily, but each new filter option increases the complexity geometrically. 

## Possibility 2: a nod to the future

* Remove the filter counts

  <img width="733" alt="Screen Shot 2019-11-21 at 17 13 10" src="https://user-images.githubusercontent.com/221614/69382095-55079c80-0c84-11ea-933c-b7a308e6c401.png">

* ...but otherwise, keep current filtering logic _unchanged_. This means _buggy_. However, without the numbers, the bugs will be less noticeable.

This option keeps the buggy filters around, which gives potential users an idea of what they can expect in the future, though this may cause more frustration than optimism.

## Regardless, fix searching and sorting

Whichever path we choose, we need to fix sorting and searching (unless we get rid of searching?). These need to query GitHub, rather than acting upon the set of issues already in the browser.

**Comment by stellarmagnet** [comment]
After looking at what Zenhub, Github, Gitcoin and Bounties Network do, I have concluded that adding numbers is overkill. In fact, this was never in the original design of the Projects app. I say we remove it.

I'm not sure yet about Possibility #1. Let's just make filters a little less buggy, then do some more user research to see what people expect out of filtering. Restricting the Projects app filtering to a single repo seems fine, and will help with our querying. I'd just keep the issues tab, and make the Projects dropdown a single select dropdown, and hence remove the tile with the "x" where you can remove the project.

> Whichever path we choose, we need to fix sorting and searching (unless we get rid of searching?). These need to query GitHub, rather than acting upon the set of issues already in the browser.
Agreed. I think search is still important to keep, and perhaps the single repo way can help with querying.

Re: some comments from here: https://github.com/AutarkLabs/open-enterprise/issues/1488#issuecomment-556404941
> If we select one kind of label ("Help Wanted," say), then we should get only issues with that label. If we then select another label ("Good First Issue"), we should get more issues; all issues with either label.

Github and Zenhub do not show more issues when you select multiple labels. I think it's fine if ours is operating like that.

**Comment by chadoh** [comment]
> I'd keep the other filters and I'd keep the issues tab, and make the Projects dropdown a single select dropdown, and hence remove the tile with the "x" where you can remove the project.

I'd love to hear if @jayalaves has any thoughts about the best way to approach this. My thought: if you can only select one Project at a time, I'd rather get rid of "Project" from the FilterBar entirely, and require going back to Overview to select a different project.

> I'm not sure yet about Possibility #1. Let's... do some more user research to see what people expect out of filtering.

Depending on how we do user research, I think having fewer-but-fully-functional interface elements, rather than more-but-slightly-clumsy, will put us in a place of strength. But that's only relevant if our user research will involve seeing how users interact with our actual app, as opposed to some simpler form of user research, such as questionnaires.

> make filters a little less buggy

This could mean so many things 😄

If we remove the filter counts and only allow selecting one project at a time, do you think current filter behavior is good enough? What remaining bugs do we need to address? Do we need to make sure we re-query GitHub every time a new filter is selected?

> Github and Zenhub do not show more issues when you select multiple labels

Fascinating! So they're using "AND" to join all the label filters. "Issues that have `ui-perfection` AND `a11y`" – that seems less useful to me, but it will definitely be easier to copy their functionality, just based on the fact that if we're querying GitHub every time a new filter is selected, we will literally be using their search functionality.

**Comment by javieralaves** [comment]
Temporarily closing this for now, now than we're addressing filtering with the Projects detail view in Sprint C1.
