### ISSUE TITLE
Ensure that our the Istanbul hardfork won't break the OE apps

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1701]
### Acceptance Criteria
- [ ] Ensure that none of our app contracts (and external ones, such as StandardBounties) are coded in a way where the Istanbul fork will break it.
- [ ] Respond to this issue certifying that the analysis was completed.

I assume MixBytes may have caught anything in the audit, right? Since the details of the fork were understood while the audit was taking place.

**Comment by javieralaves** [comment]
@stellarmagnet Moved this from the product repo to the open-enterprise repo and put the acceptance criteria in the original description.

**Comment by stellarmagnet** [comment]
Closing this, not needed
