### ISSUE TITLE
Allocations: add a margin to budget cards in tablet-sized views

### ISSUE THREAD

**Issue by e18r** [AutarkLabs/open-enterprise#1702]
In tablet-sized views, budget cards lack a left margin:
![Screenshot from 2019-12-03 10-47-08](https://user-images.githubusercontent.com/16065447/70066427-b3a11480-15ba-11ea-8e1a-cc317cf70515.png)

Add a left margin to make them look more similar to the desktop version:
![Screenshot from 2019-12-03 10-50-47](https://user-images.githubusercontent.com/16065447/70066496-d3d0d380-15ba-11ea-89a1-8da4603492c8.png)

**Comment by chadoh** [comment]
@javieralaves what do you think of this? I think most elements go right to the edge in tablet-width and smaller, in aragonUI. If there are two budget cards here and the right one also goes right to the edge, would that make it feel ok?

**Comment by chadoh** [comment]
We could incorporate this into #1573 and close this issue
