### ISSUE TITLE
Projects/Submit application: Estimated completion date shouldn't be in the past

### ISSUE THREAD

**Issue by e18r** [AutarkLabs/open-enterprise#1715]
The submit application panel allows submitting applications with dates in the past, which later fail at the transaction stage.
![Screenshot from 2019-12-03 15-54-06](https://user-images.githubusercontent.com/16065447/70088962-46ef3f80-15e5-11ea-99cc-d63bd3525475.png)

Add an error message so that estimated completion dates can't be in the past.

**Comment by e18r** [comment]
Upon further inspection, completion dates in the past don't fail at the transaction level. They just show up as if they hadn't been set. Since the completion date is an optional field, I think this behavior is reasonable. Should we close this ticket then? @Quazia

**Comment by Quazia** [comment]
Can you explain the behavior it gives a little better? I still feel like it shouldn't be possible to have an estimated completion date in the past, and the front end validation shouldn't be too bad for that.

**Comment by e18r** [comment]
Sure. So when the bounty hunter submits an application, they have to specify a work plan, check some checkboxes, and there are two optional fields: estimated hours and estimated completion.
![Screenshot from 2019-12-03 15-54-06](https://user-images.githubusercontent.com/16065447/70088962-46ef3f80-15e5-11ea-99cc-d63bd3525475.png)

The bounty hunter can leave them blank or type whatever they want, I don't think there's any type of form validation in these two fields. So when the bounty hunter inputs a date in the past, the front end allows them to. But so does the contract as well, since it accepts the transaction and then assumes that the user didn't input a date at all.

It might make sense at some point to restrict this at the contract level, but until then I feel like restricting it only at the UI level is adding unnecessary hassle to the user.

**Comment by stellarmagnet** [comment]
@e18r there is no concept of estimated completion date at the contract level. this is metadata stored on an IPFS file, and is just for project management purposes. i can see use cases for why we would want to allow past completion dates -- this is if someone is "applying" for a bounty for work that they completed before they applied. probably wont be a common scenario, but i can envision it occurring. hence, I will close this ticket.
