### ISSUE TITLE
Add "Deactivate/Activate budget" functionality

### ISSUE THREAD

**Issue by chadoh** [AutarkLabs/open-enterprise#1723]
- [ ] When deactivate is selected, a confirmation modal will be displayed. If the user clicks the “Deactivate” button in the confirmation modal, a transaction signing panel will be opened (maybe skip this; see discussion in [Google Doc](https://docs.google.com/document/d/1tSKskxkaJQZZAhilC8xh2jjYxLJxkUqOhCn071pHAN0); if we can skip this, then remove the currently-commented-out code)
- [ ] Functionally, deactivate means setting the budget to 0. We should enhance the radspec to conditionally display a different message when the _amount is zero. E.g. Deactivate "Marketing" budget

**Comment by javieralaves** [comment]
Looks good, but as of right now the 'New allocation' option is still there when it shouldn't, and the icon is not the correct one. I presume this is currently being addressed by @chadoh's latest update.

![Screenshot 2019-12-13 at 10.51.18.png](https://images.zenhubusercontent.com/5cf4fe30c7859b3c51c81634/2b0f0b18-9f50-4aa2-88f8-466af6c956bf)

**Comment by javieralaves** [comment]
Tested this on the continuous deploy from December 17th, 2019.

✅ Looks great!
