### ISSUE TITLE
Improve New Allocation panel

### ISSUE THREAD

**Issue by chadoh** [AutarkLabs/open-enterprise#1731]
See [Figma frame D 1.3](https://www.figma.com/file/9c4GAhAa1LhH1TmJC8vCHA/Allocations?node-id=878%3A26926) for current designs. Screenshot:

![design mockup](https://user-images.githubusercontent.com/221614/70544097-84018780-1b39-11ea-96f4-2d30cffe048a.png)

* Update styling of the labels (Look at the NewBudget panel, those are the correct styles)
* Update how we articulate "Available Funds" – instead of current two-liner, conditionally display Available Funds as either 1. the funds remaining in the budget or 2. as the funds available in the vault depending on the following:
  * If Available in Vault < Available in Budget, Available Funds = Available in Vault
    “Available funds: x” (where x is the amount available in vault)
  * If Available in Vault > Available in Budget, Available Funds = Available in Budget
    “Available funds: x” (where x is the amount available in budget)

Text for help component next to ‘Available funds’ displays the following text:

> **Available funds** displays the amount of funds remaining within this allocation’s budget. If this amount exceeds the organization’s vault funds, an accordingly adjusted value will be shown here.

**Comment by javieralaves** [comment]
@chadoh You accidentally created this issue on the product repo :) I transferred it to open-enterprise, but you have to reassign it to the epic. I’m not able to do this on my phone right now

**Comment by javieralaves** [comment]
Will be able to test once fix to #1642 is deployed.

**Comment by javieralaves** [comment]
@chadoh @PeterMPhillips Not sure this is 100% good to go. Have a look at what the help component displays to me today:
![Screenshot 2019-12-20 at 07.57.58.png](https://images.zenhubusercontent.com/5cf4fe30c7859b3c51c81634/049e1389-9e4c-4ab1-b661-d771a52a5b0e)
December 17th was three days ago, and as far as I can tell this DAO has a manually defined period duration of a day, so if anything it should probably say 'until 20 December 2019'.

**Comment by stellarmagnet** [comment]
@javieralaves why do you think it has a period duration of a day?

**Comment by javieralaves** [comment]
@stellarmagnet Have a look [at the link](https://rinkeby.aragon.org/#/neudune/0x66cad2ce53968d08461cfb0b71568d66f2985d4f/) and have a look at the metrics panel, or click on the `New budget` button. You'll notice that the duration is 1 day.

**Comment by javieralaves** [comment]
That said, [it works well here](https://rinkeby.aragon.org/#/bananatornado/0x665c824df722f09566fe8b04376a52c8b4c9aeb1/) given the latest general deploy to Rinkeby, so I'm marking this one off considering that most organizations will for now have a 30 day period and won't run into the edge case I potentially found earlier.
