### ISSUE TITLE
Update Projects Issues tab

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#1736]
Update the bounty-related information with the new icons and terms in the design

Note: These specs are associated to a single bounty logic, while the Figma designs extend to multi-bounty logic. Please integrate these specs before moving into multi-bounty logic.
![ProjectsIssuesTabSnip](https://user-images.githubusercontent.com/6549550/70291930-a9456d00-17aa-11ea-8117-852752755ecd.PNG)

**Comment by rkzel** [comment]
Icons and texts are the same for OpenSubmission bounties, @javieralaves ? So in OS there would be "accepting work" instead of "accepting applications"?

**Comment by javieralaves** [comment]
@rkzel Great point, apologies for not making this clearer. It would be 'Accepting work submissions', to keep it consistent with the information displayed in the 'Bounty' widget within the detail view.
