### ISSUE TITLE
Adjust logic and format for Projects Bounties Context Menu

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#1738]
Make sure that context menus are consistent with the following specifications

Context menus
Issue not funded

- 'Fund issue' ('Coins' icon + text)

Issue funded without application required
- 'Submit work' ('File' icon + text)

Issue funded without application required + submissions submitted

- 'Submit work' ('File' icon + text)
- 'View work submissions' ('View' icon + text)
- 

Issue funded with application required

- 'Submit application' ('File' icon + text)

Issue funded with application required + application submitted

- 'Submit application' ('File' icon + text)
- 'View application' ('View' icon + text)

Issue funded with application required + application submitted (more than one)

- 'Submit application' ('File' icon + text)
- 'View applications' ('View' icon + text)
- 

Issue funded with application required + application assigned
Assignee view

- 'Submit work' ('File' icon + text)
- 'View applications' ('View' icon + text)
- Public view
- 'View applications' ('View' icon + text)

Issue funded with application required + work submitted

- 'View work submissions' ('View' icon + text)
- 'View applications' ('View’' icon + text)
- 

Issue funded with application required + work approved

- 'View work submissions' ('View' icon + text)
- 'View applications' ('View' icon + text)

Bounty completed

- 'View work submissions' ('View' icon + text)
- 'View applications' ('View' icon + text)

How to render the action text when there is single vs. multiple

- If there is a single application, display “View application”
- If there are multiple applications, display “View applications (2)”
- If there is a single work submission, display “View work submission”
- If there are multiple work submissions, display “View work submissions (2)”
- When either of these action menu items are selected, the panel will be opened and the application or work that was submitted most recently will be opened.

**Comment by rkzel** [comment]
Done!
