### ISSUE TITLE
Add open submission funding flow for bounties

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#1739]
‘Fund issue’ panel

- Include an additional section labelled ‘Work terms’ underneath the ‘Description’ input box, which includes a “Switch” component that is labeled with “Applications required to work on issues”
- This Switch component is set off by default, which means that the bountie(s) won’t require applications for submitting work
![WorkFundingPanel](https://user-images.githubusercontent.com/6549550/70294982-545a2480-17b3-11ea-8411-d97c58eb2216.PNG)

**Comment by rkzel** [comment]
One thing I'm missing is what the Help (?) button should say - please help, @javieralaves @stellarmagnet  :)

**Comment by javieralaves** [comment]
@rkzel I'll facilitate these texts very soon!

**Comment by stellarmagnet** [comment]
Can we call this "open submission" in the title? i got confused and thought this was user-funded from their wallets

**Comment by rkzel** [comment]
Done!
