### ISSUE TITLE
Allocations table: use double-check icon & colors

### ISSUE THREAD

**Issue by chadoh** [AutarkLabs/open-enterprise#1763]
## Current implementation:

![current.png](https://images.zenhubusercontent.com/5699129a638e718c99601ac2/1963ab3e-fd55-4c2e-80e0-4f30933b44b8)

## Design:

(See [Figma frame D 1.0](https://www.figma.com/file/9c4GAhAa1LhH1TmJC8vCHA/Allocations?node-id=878%3A27441) for latest)

![design.png](https://images.zenhubusercontent.com/5699129a638e718c99601ac2/f42d5f8f-bc72-44bd-9e7f-d09de9aaea6b)

"Enacted" text color: ~`theme.accent`~ `theme.positive` (`#2CC68F`)

**Comment by chadoh** [comment]
Note that we already started using the double checkmark icon in the Rewards app in #1754

**Comment by topocount** [comment]
@javieralaves Shouldn't this be closed or at least in review? I merged a PR where the double-check was added.

**Comment by javieralaves** [comment]
@topocount I see the double-check in Projects for example, but not in Allocations. [Have a look](https://rinkeby.aragon.org/#/bananatornado/0x665c824df722f09566fe8b04376a52c8b4c9aeb1/).
<img width="1440" alt="Screenshot 2019-12-20 at 15 19 13" src="https://user-images.githubusercontent.com/28843778/71260863-34db0400-233c-11ea-95c8-b8f3a39baf70.png">
<img width="1440" alt="Screenshot 2019-12-20 at 15 20 21" src="https://user-images.githubusercontent.com/28843778/71260883-42908980-233c-11ea-9c7d-cb8b97a9ab29.png">
