### ISSUE TITLE
Guide linked in Getting Started doc leads to error page

### ISSUE THREAD

**Issue by john-light** [AutarkLabs/open-enterprise#1774]
**Describe the bug**
When I click the guide link in the [Getting Started](https://github.com/AutarkLabs/open-enterprise/blob/master/docs/GETTING_STARTED.md) doc I am taken to a page with this error message:

> Error: could not handle the request

**Comment by javieralaves** [comment]
@stellarmagnet and I don't seem able to reproduce this error. @john-light could you check with a different device or browser?

**Comment by john-light** [comment]
@javieralaves  seems to be back up now, closing
