### ISSUE TITLE
Create Panel to start a new Dot Vote

### ISSUE THREAD

**Issue by PeterMPhillips** [AutarkLabs/open-enterprise#1784]
Panel should have a 'Question' field along with the option to add an arbitrary number of choices. Upon submit the contract's `newVote` function should be called with an empty `_executionScript` being passed to the function.

Be sure to have 'New vote' buttons in the Empty card and the Header

**Comment by javieralaves** [comment]
Tested on [Rinkeby](https://rinkeby.aragon.org/#/autarkdao/0xb580bfb4704ed1ab09d75b43dfa23f19d4ab315d/) and looking good! ✅
