### ISSUE TITLE
Ensure filtering includes the Dot Voting app

### ISSUE THREAD

**Issue by PeterMPhillips** [AutarkLabs/open-enterprise#1785]
Right now we can filter for Allocations and Projects. Add Dot Voting as an option in the filter bar

**Comment by javieralaves** [comment]
Tested on [Rinkeby](https://rinkeby.aragon.org/#/autarkdao/0xb580bfb4704ed1ab09d75b43dfa23f19d4ab315d/) and looking good! ✅
