### ISSUE TITLE
Make 'Execute Vote' button conditional

### ISSUE THREAD

**Issue by PeterMPhillips** [AutarkLabs/open-enterprise#1786]
Make the 'Execute Vote' button conditional so that it doesn't appear when there is an informative vote from Dot Voting or Projects

**Comment by javieralaves** [comment]
Tested on the [continuous deploy DAO](https://rinkeby.aragon.org/#/neudune/0x6bee7a14a2979629b7f6c29279bc0c6808712d97/) and works as expected! ✅
