### ISSUE TITLE
Unable to remove projects

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1791]
Whenever I try to remove a project, I get the following when performing the vote:

![image](https://user-images.githubusercontent.com/2584493/70999673-28577100-20da-11ea-886f-36a52a25b4f7.png)

DAO:
https://rinkeby.aragon.org/#/neudune
https://mainnet.aragon.org/#/climatestrike

**Comment by Quazia** [comment]
This is specifically an issue with Projects that have already been removed; when pulling the repo information and feeding it into the function to _remove_ the repo the params need to be massaged.

**Comment by e18r** [comment]
I'm closing this ticket since it actually encompasses two problems for which I created specific tickets:

1. When trying to remove a project with active bounties. See #1855 
2. When a project's GitHub repo gets deleted. See #1858
