### ISSUE TITLE
Review Work Panel cannot show multiple submissions

### ISSUE THREAD

**Issue by topocount** [AutarkLabs/open-enterprise#1818]
**Describe the bug**
The review work panel is not set up to allow selection between various submissions

When clicking on a link in the activity feed for different submissions, only the most recent submission shows in the panel and there is no way to access earlier submissions.

![Peek 2019-12-20 11-03](https://user-images.githubusercontent.com/17910833/71270934-6a6df600-2318-11ea-8626-5841033a7088.gif)

**Comment by javieralaves** [comment]
Good catch!

**Comment by javieralaves** [comment]
Reviewed this [on Rinkeby] (https://rinkeby.aragon.org/#/autarkdao/0xbbfb20abf5d19709c4b97722e37c73cada0bc7ca/issues/MDU6SXNzdWU1NDA4ODY0MjU%3D) on January 3 2020. Looks good!
