### ISSUE TITLE
Text overflows in issue detail

### ISSUE THREAD

**Issue by topocount** [AutarkLabs/open-enterprise#1822]
I think filling out our bug template leads to some unexpected text overflow in Projects Also pictures don't render too well and should probably be scaled to fit width

[Update: this doesn't only happen on our bug template. Any issue with a long link or large image shows up similarly]

![image](https://user-images.githubusercontent.com/17910833/71299074-0287d180-2351-11ea-9882-be2a5784042c.png)

**Comment by javieralaves** [comment]
Reviewing this [on Rinkeby](https://rinkeby.aragon.org/#/autarkdao/0xbbfb20abf5d19709c4b97722e37c73cada0bc7ca/issues/MDU6SXNzdWU1NDEwNjUzOTQ%3D) on January 3 2020. Looks good!
