### ISSUE TITLE
Allocations: budget name needs to wrap

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1828]
The budget name is not wrapping... It should wrap and truncate after 2 lines

![image](https://user-images.githubusercontent.com/2584493/71312340-d8561280-2429-11ea-86d7-ccd9c832b082.png)

**Comment by javieralaves** [comment]
Reviewed this update [on Rinkeby](https://rinkeby.aragon.org/#/autarkdao/0x8897929bedb88949fd3717ea9493896d3e17bdd5/) on January 3 2020. Looks good to go!
