### ISSUE TITLE
Decimal place issues with Dot Voting detail view

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1845]
Since our last release, something happened with the Allocation amounts per option on the Dot Voting  detail view - we are showing too many zeros.

![image](https://user-images.githubusercontent.com/2584493/71813952-53026d00-307b-11ea-8ab5-cf1d3106b0d6.png)

**Comment by javieralaves** [comment]
Tested on the continuous deploy DAO and works as expected! ✅
