### ISSUE TITLE
About app: side panel opening without animation

### ISSUE THREAD

**Issue by e18r** [AutarkLabs/open-enterprise#1854]
In the About app, the side panel opens immediately without the sliding animation.

![](https://user-images.githubusercontent.com/221614/72002728-f6878500-3215-11ea-92ba-90fb782d1bdf.gif)

This is caused by the `onCodeMirrorInit` function passed to the `CodeMirror` component in `app/src/shared/components/MarkdownEditor.js`:
![Screenshot from 2020-01-08 14-14-59](https://user-images.githubusercontent.com/16065447/72008206-5172a980-3221-11ea-8e74-86f475a55a99.png)

Bring the side panel opening animation back.

**Comment by stellarmagnet** [comment]
This seems resolved
