### ISSUE TITLE
Rewards: "Action Impossible" while voting on a recurring dividend

### ISSUE THREAD

**Issue by e18r** [AutarkLabs/open-enterprise#1857]
## Ticket status
This ticket needs more research in order to reach a reproducible state.

## Description
*Sometimes*, when trying to vote to create a recurring dividend, an "Action Impossible" message shows up.

## Steps taken by the user (@edlondon)
1. Create a DAO where reward creation is handled by voting
2. Create a recurring dividend
![newReward](https://user-images.githubusercontent.com/16065447/72071800-9eef2500-32ba-11ea-8d39-9ffe86769251.png)
3. Go to Voting
![voting](https://user-images.githubusercontent.com/16065447/72071918-deb60c80-32ba-11ea-84e9-61edba222fbb.png)
4. Click on "Yes"
![vote](https://user-images.githubusercontent.com/16065447/72071990-0907ca00-32bb-11ea-9e00-b5614b5dec0f.png)
5. An "Action Impossible" message shows up
![actionImpossible](https://user-images.githubusercontent.com/16065447/72072106-40767680-32bb-11ea-8488-9131a8939587.png)
6. A few hours later, the vote works with the same user
![6CEF5C13-019F-4A25-9745-BF04F7E85048](https://user-images.githubusercontent.com/16065447/72096087-834e4380-32e7-11ea-8582-ebb97ca6cefb.jpg)

## Expected behavior
The user should be able to vote to create the recurring dividend immediately

**Comment by javieralaves** [comment]
Closing this after having been able to resolve the issue with Ed. We set up a custom permission for him to be able to create a reward with a custom address instead of having to go through Voting. The transaction took 13-15 minutes to go through but it worked.
