### ISSUE TITLE
Create issues objects and cards for display in 'Bounties' tab swimlanes

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#1862]
This should cover the following acceptance criteria:

- [ ]  Issues are sorted automatically by creation date ascending (newest first) across pipelines

- [ ]  Issues can be clicked on to navigate directly to the issue detail view

![image](https://user-images.githubusercontent.com/6549550/72575471-870b3880-389a-11ea-8dd8-5ea30665155a.png)

**Comment by javieralaves** [comment]
Reviewed in [CD](https://rinkeby.aragon.org/#/neudune/0xe3fc72a7f3dda98a0a76863c9aad73968c6c0c42/bounties) and works as expected!
