### ISSUE TITLE
Create basic structure for 'Bounties' Tab

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#1863]
This should cover the following acceptance criteria:
 

- [ ]  Three pipelines available: 'Accepting applications', 'Accepting work submissions' and 'Review'
![image](https://user-images.githubusercontent.com/6549550/72575435-604d0200-389a-11ea-8bfd-55750f219e56.png)

This just handles adding the defailt view, with no issues or filtering logic.

**Comment by javieralaves** [comment]
Reviewed in [CD](https://rinkeby.aragon.org/#/neudune/0xe3fc72a7f3dda98a0a76863c9aad73968c6c0c42/bounties) and works as expected!
