### ISSUE TITLE
Add basic 'Bounties' Tab with navigation to blank Bounties page

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#1864]
Add the Bounties tap to the Projects app;
![image](https://user-images.githubusercontent.com/6549550/72162655-586bfa00-3390-11ea-80c3-0223f120110d.png)
When clicking this tab it should navigate to an _empty_ Bounties page.
This issue covers the basic page creation and routing, but _not_ the general structure of the swimlanes and Bounties page.

**Comment by javieralaves** [comment]
Reviewed in [CD](https://rinkeby.aragon.org/#/neudune/0xe3fc72a7f3dda98a0a76863c9aad73968c6c0c42/bounties) and works as expected!
