### ISSUE TITLE
Restructure search/filtering and move it to the new Project detail view

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#1866]
This issue should cover the following acceptance criteria:

- [ ]  Issues in a project detail view can be filtered based on the rules defined in the spec
- [ ]  Issues in a project detail view can be searched
- [ ]  A 'Not found' state is triggered when no results are found
- [ ]  Issues in a project detail view can be sorted by creation date, alphabetically, by value and by bounty phase

For this issue, bring the basic filter bar over from the Issues view, and modify it to fit the product specifications and figma design:
![image](https://user-images.githubusercontent.com/6549550/72164451-b5b57a80-3393-11ea-80cf-43d31994e6e7.png)

[For more information on filter and sort behavior see the product specifications](https://docs.google.com/document/d/185wMhoDQ4h1G51MLkRzLtqYDdybm3JzRlYCvPR0iC5Y/view#heading=h.titsc9k35yvd)

This issue should be the last instance of us needing assets from the Issue view so the expectation is also that all assets from the Issues view will be cleaned up in this ticket.

**Comment by chadoh** [comment]
If we rename `Issues` to `ProjectDetail`, I think this will be a natural part of #1865
