### ISSUE TITLE
Move issue display from 'Issues' tab to Projects detail views

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#1867]
This issue includes moving the issue list display over from the 'Issues' tab to the project detail view. Upon completion all issues should be displayed upon navigation to the projects detail view with a [default sort](https://docs.google.com/document/d/185wMhoDQ4h1G51MLkRzLtqYDdybm3JzRlYCvPR0iC5Y/edit?disco=AAAAEGaYJ4k)

Adding the filter bar or any search/filter functionality is out of scope.
![image](https://user-images.githubusercontent.com/6549550/72164044-fc56a500-3392-11ea-8aae-b28509225d7e.png)

**Comment by chadoh** [comment]
If we rename `Issues` to `ProjectDetail`, I think this will be a natural part of #1865
