### ISSUE TITLE
Add 'New Issue' button to project detail view

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#1868]
This issue should fulfill the following acceptance criteria:

- [ ]  'New issue' is the global button in project detail view, and once clicked, it will be pre-populated to the project from which the button was clicked

When this issue is finished all of the functionality exposed in Figma should be functional in the project detail view

![image](https://user-images.githubusercontent.com/6549550/72165080-d6320480-3394-11ea-9622-34e5b17de560.png)

The main change that needs to be made here is the _pre-population_ of the function call. Other than this it should be functionally identical to the previous `New Issue` button.

**Comment by chadoh** [comment]
If we rename `Issues` to `ProjectDetail`, I think this will be a natural part of #1865
