### ISSUE TITLE
Modify widgets to have primary/secondary selectors on create

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#1879]
This issue should cover the following acceptance criteria:

- [ ] Widgets can be added to a primary and secondary column

![image](https://user-images.githubusercontent.com/6549550/72353331-e6f2bb00-36b1-11ea-81ec-d61e8775e64d.png)
When bringing up a `New widget` panel, there should be drop down selectors for Primary, and Secondary columns.

![image](https://user-images.githubusercontent.com/6549550/72353427-1275a580-36b2-11ea-84b3-633d8a624fc3.png)
Once the widget has been loaded it should display in the appropriate column, (a) primary or (b) secondary.

There should be some logic for handling widget positioning in `PanelContent.js`. What must be added is the drop down to select positioning, and then a check must be handled against the display logic that currently exists for this positioning.

Currently, the `New Widget` panel, has a `Type` field, this should be the `source` field for the `Markdown` widget. 

In addition we need a `Widget` drop down, but for now the only option would be `Markdown`.

Other options for the `Widget` drop down will be added in subsequent tickets.

**Comment by ottodevs** [comment]
This estimation should be increased a bit, as it is presented as an static layout when in fact it carries with calculations and dynamic state that makes the logic quite complex.

It does not take in account multiple widgets for the same column and it took extra effort to make it consistent with the designs.

My take on this was a 5 at least.

**Comment by ottodevs** [comment]
Done in AutarkLabs/about#54
