### ISSUE TITLE
Modify widgets so position can be changed

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#1880]
Acceptance criteria:
- [ ] Widgets can be repositioned within their column and between columns

1. Create an Actions dropdown on the top right corner, which has "New widget" and "Edit layout" buttons.
![Screenshot from 2020-01-14 12-06-53](https://user-images.githubusercontent.com/16065447/72365509-62f6fe00-36c6-11ea-9125-0cbb28210d9a.png)

2. When the "Edit layout" button is clicked, two buttons appear, "Cancel" and "Submit".
![Screenshot from 2020-01-14 12-07-20](https://user-images.githubusercontent.com/16065447/72365554-71ddb080-36c6-11ea-89e0-ea246ae7e77e.png)

3. On every widget header, navigation arrows should appear. Left and right should always be present, and down and up should only be present if there are other widgets in the same column.
![Screenshot from 2020-01-14 12-07-47](https://user-images.githubusercontent.com/16065447/72365623-933e9c80-36c6-11ea-9ff1-d185178a0d69.png)
![Screenshot from 2020-01-14 12-08-11](https://user-images.githubusercontent.com/16065447/72365631-96398d00-36c6-11ea-9f0b-327bf6dcf417.png)

4. Clicking these navigation arrows allows the widgets to be repositioned

5. Clicking on "Cancel" reverts all the changes
6. Clicking on "Submit" saves all the changes

In order to handle the position of widgets, the contract needs to be updated with a  "position" CID (`updateWidget('POSITION_LAYOUT', this_is_a_cid)`, this CID will link into the individual widget CIDs and attach position data at the top level. This way the CID will only change when there are discrete differences in the layout change, and that layout is itself unique compared to other layouts that have been used previously.

[Currently widgets are only being set ](https://github.com/AutarkLabs/about/blob/61b39bb26dbb1f7a86abced043f33b6fe8498e0f/app/src/components/panel/PanelContent.js#L141)as either `PRIMARY` or `SECONDARY`, going forward we would maintain a _single_ CID (the `POSITION_LAYOUT` CID) that contains both the layout information, and the CIDs of all of the individual widgets. This means on both a `new widget` call, and an `update widget` call this CID would need to be updated.

**Comment by javieralaves** [comment]
> On every widget header, navigation arrows should appear. Left and right should always be present, and down and up should only be present if there are other widgets in the same column.

@Quazia What if there's only one full-width column because secondary column issues were never added? In that case, if there's only one widget, there'd be no navigation controls; and if there were more than one, there'd only be up and down navigation controls.

**Comment by ottodevs** [comment]
Partially done in AutarkLabs/about#54
