### ISSUE TITLE
Add basic votes widget

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#1881]
This issue should cover part of the following acceptance criteria:

- [ ] Users can add markdown, votes and dot votes widgets

![image](https://user-images.githubusercontent.com/6549550/72368116-6c369980-36cb-11ea-8249-ab371d0bff43.png)

1. When navigating to the `new widget panel` the user should have the option to add `Latest Votes`
2. For this issue this action will simply create an empty widget with the 'Latest Votes' title.

**Comment by javieralaves** [comment]
Tested in the [experimental client](https://beta.autark.xyz/#/0xe19691d098730ad377835590AB900221D7212417/0xd50e6f8d8975a9c5985ececfd5dbcc7870a7b2e0/), works as expected! (minus some minor details that I'm checking with Emilio for quick fixing)
