### ISSUE TITLE
Pull Vote app data into About app

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#1883]
This issue should cover part of the following acceptance criteria:

- [ ] Users can add markdown, votes and dot votes widgets

In order to display latest vote information the About application needs to be connected with the Voting application as an external contract so that events can be adding to the About app state.

This issue covers modifications to the `script.js` [file ](https://github.com/AutarkLabs/about/blob/master/app/src/script.js#L29)to connect to the first, or the default, voting application [as an external contract](https://hack.aragon.org/docs/api-js-ref-api#external) to receive the event information. In order to connect to the voting application, we can use the [`installedApps`](https://hack.aragon.org/docs/api-js-ref-api#installedapps) endpoint in aragon.js.

a `Votes` object should be loaded into state, with sufficient information to display the following widget:

![image](https://user-images.githubusercontent.com/6549550/72368500-32b25e00-36cc-11ea-97e7-4a296e1bf2f6.png)

**Comment by e18r** [comment]
I just changed the estimate to reflect the fact that the store needed to be upgraded. This won't affect the delivery date.

**Comment by javieralaves** [comment]
Tested in the [experimental client](https://beta.autark.xyz/#/0xe19691d098730ad377835590AB900221D7212417/0xd50e6f8d8975a9c5985ececfd5dbcc7870a7b2e0/), works as expected!
