### ISSUE TITLE
Changes to Projects card display

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#1895]
This issue should cover the following acceptance criteria:

- [ ]  Project card displays bounties instead of commits
- [ ]  Project card displays GitHub identifier for GitHub projects

![image](https://user-images.githubusercontent.com/6549550/72574148-0b0ef180-3896-11ea-8188-0098a8176a16.png)

Conditionally render the Github identifier on Github projects, and make sure the bottom is displaying the number of bounties.

**Comment by javieralaves** [comment]
Tested on the [continuous deploy DAO](https://rinkeby.aragon.org/#/neudune/0x6bee7a14a2979629b7f6c29279bc0c6808712d97/) and works as expected! ✅
