### ISSUE TITLE
Dot Voting dark mode -- bar should be dark blue instead of white

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1959]
We need to make updates to the Dot Vote card and the Dot Vote detail page

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/252add6f-16c3-4f6a-9835-c452702a8b1a)

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/dfd18d00-93b4-40e4-b5d0-8f0498f5de4e)

**Comment by javieralaves** [comment]
Reviewed on Rinkeby, looks good!
