### ISSUE TITLE
Advanced OE template: Need to set oracle for 2nd token

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1961]
Steps to reproduce:

- Create Org
- Select OE template
- Select 2 tokens
- Set up both tokens as non-transferable
- Mint yourself some of the tokens during the OE setup flow
- Launch DAO
- Add each of the token addresses to your Metamask wallet (so you can attempt sending them), then try sending the tokens...

You'll see that:
1) The first token is non-transferable (the transfer fails - as expected)
2) The second is UNEXPECTEDLY transferable (the transfer succeeds)

Expected: Both tokens should be non-transferable

Solution:
- We need to move this line outside of the conditional operator: https://github.com/AutarkLabs/open-enterprise/blob/608744d4e2970a3b1c595f2f9df045c0b309a140/templates/open-enterprise/contracts/OpenEnterpriseTemplate.sol#L87

Right now if the first token is non-transferable, then it bypasses this step and we are unable to setup the Oracle for the 2nd token manager.

**Comment by ottodevs** [comment]
> Steps to reproduce:
> 
> * Create Org
> * Select OE template
> * Select 2 tokens
> * Set up both as transferable

@stellarmagnet I asume you meant "Set up both as **NON** transferable, right?

**Comment by stellarmagnet** [comment]
@ottodevs yes that is correct, my bad! Updating the description

**Comment by javieralaves** [comment]
Trying to reproduce this [here](https://beta.autark.xyz/#/javi4/0x7710902c071d552015bef2a8421f9b3dabffcb1a/)... I've set both to non-transferable. Do I try now to transfer them? cc @ottodevs
