### ISSUE TITLE
Can't create new project

### ISSUE THREAD

**Issue by macor161** [AutarkLabs/open-enterprise#2005]
**Describe the bug**

With a new DAO created from the Open Enterprise template, in the Projects app:

1. Click "New project"
2. Enter "Test" as title and "Test" as description
3. Click "Submit" and wait for the transaction to succeed
4. In the voting app, getting the following error: `The action failed to execute. You may not have the required permissions.`

**Mainnet or testnet?**
Rinkeby

**Expected behavior**
The vote should pass and add the new project.

**Desktop (please complete the following information):**
 - Mac
 - Chrome 81

**Comment by topocount** [comment]
@macor161 apologies about this. I've just published a fix and tested it so you should be good to go. This was originally a publishing issue, so no code changes were needed to fix this.

**Comment by macor161** [comment]
Thanks @topocount 🙂
