### ISSUE TITLE
Overview tab: leaderboard / sidebar

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#440]
The leaderboard will display the top accounts that have earned rewards.

[Specs](https://docs.google.com/document/d/1Ub332Ad8aRXmJJ7klWoQ2ogHLdYy8fzE5RrKkUnKd6A/edit#heading=h.5v0q08q0nfd)

[Design](https://projects.invisionapp.com/d/main#/console/14716432/332905229/preview)

**Comment by javieralaves** [comment]
Addressed by the specs in 'Enhanced Rewards' in the product repo.
