### ISSUE TITLE
Issue Curation panel: It is possible to send a transaction without issues selected for curation

### ISSUE THREAD

**Issue by ottodevs** [AutarkLabs/open-enterprise#462]
![image](https://user-images.githubusercontent.com/5030059/53219098-f8c50d00-365e-11e9-9603-4cc4cc589236.png)
By using the remove buttons one is able to remove every issue and submit an empty curation, and the transaction goes on. We should disable the "minus" icon once there is only one issue displayed.

**Comment by rkzel** [comment]
That's been solved many moons ago...

**Comment by javieralaves** [comment]
Tested this in the continuous deploy from December 17th, 2019.

✅ Everything works as expected!
