### ISSUE TITLE
Status logic when >1 bounty is available

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#502]
- [x] Hide “Slots Available” in New Bounty Allocation Panel
- [x] Hide “Slots Available” column on Issue Detail
- [ ] Ensure the bounty status follows the logic below

* Accepting applicants - Displayed when the bounty is funded and there are NO pending applications, NO work in progress, and NO work ready for review
  * In this stage, multiple people can submit applications
* Pending application review - Displayed when 1 or more applications are pending review AND when there is NO work in progress and NO work ready for review.
  * In this stage, multiple people can still submit applications
* Work in progress  - Displayed when 1 or more applicants have work in progress that hasn't been submitted yet.
  * In this stage, no more applications will be accepted
  * In this stage, the accepted applicants can submit work
  * If anyone who has had their work rejected resumes working on their work, it can return to "work in progress" assuming there is no additional work to review
* Work ready for review - Displayed when 1 or more submissions are pending review. 
  * In this stage, no more applications will be accepted

Refer to this ticket for additional background on the status: https://github.com/AutarkLabs/planning-suite/issues/480

Current problem with issue detail:
![image](https://user-images.githubusercontent.com/2584493/55296355-775c5980-5418-11e9-96bd-9ee1ec40afed.png)

**Comment by Schwartz10** [comment]
@stellarmagnet for some reason can't see the design for this one
