### ISSUE TITLE
My Rewards tab: Last 12 months sidebar

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#524]
In the sidebar of the My Rewards tab, there will be a region which displays the amount of rewards that were awarded to the logged in user for the last 12 months.

[Specs](https://docs.google.com/document/d/1Ub332Ad8aRXmJJ7klWoQ2ogHLdYy8fzE5RrKkUnKd6A/edit#heading=h.32kv09uzc713)
[Designs](https://projects.invisionapp.com/d/main#/console/14716432/332905225/preview)

**Comment by javieralaves** [comment]
Addressed by the specs in 'Enhanced Rewards' in the product repo.
