### ISSUE TITLE
Improve scrolling style

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#542]
**Steps to reproduce**
(This can only be tested if you have a lot of Github repos)

Use case A
1) Navigate to the Projects app
2) Click "New Project"

Observe the dual scroll bars (see photo)

Expected behavior: There should only be a single scroll bar and it should be in the outermost edge. It should only be visible while scrolling is actively taking place.

Use case B
1) Navigate to the Projects app, and connect a few repos via "New Project
2) Click on the Issues tab
Observe the scroll bars

Expected behavior: There should only be a single scroll bar and it should be in the outermost edge. It should only be visible while scrolling is actively taking place.

Use case A
![image](https://user-images.githubusercontent.com/2584493/54282478-613b4600-459c-11e9-81eb-26153671ff09.png)

Use case B

**Comment by javieralaves** [comment]
Reviewed in the continuous deploy DAO. Looks good!
