### ISSUE TITLE
Projects designs

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#612]
- [ ] Ability to cancel a bounty
* Q: where does the bounty go if the deadline passes?
* We also need a contextual menu item to expose the "cancel" action for a bounty. This probably going to make the smart contract larger...
- [x] Issues pending curation / issue curation vote results
- [ ] Ability to view issues assigned to you
- [x] Issues pending funding
- [ ] Github bot text
- [ ] Multiple bounties for single issue

**Comment by jayalaves** [comment]
Re: cancelling the bounty, I would add the option within the issue actions menu, under View on GitHub. Once clicked, you'd be asked to confirm with a subtle warning that future funding would require undergoing the bounty process again. See below:

![Remove Bounty](https://user-images.githubusercontent.com/28843778/60076085-f7980f80-9726-11e9-9030-b5104c059197.jpg)
![Confirm Remove Bounty](https://user-images.githubusercontent.com/28843778/60076102-01ba0e00-9727-11e9-953f-13d9e88d4b31.jpg)

Re: deadline termination, I suggest the bounty is automatically removed given that there are no proposals for review, and it's as if there was no bounty at all. Preferably, whoever was involved should be notified of the deadline being passed.

And re: ability to view issues assigned to you, can this be something that we incorporate as part of the filters toolbar? Maybe an additional space called Bounties with two filter options: see only tasks with bounties, and see only tasks with bounties assigned to me.
