### ISSUE TITLE
After executing a Dot Vote via side pane, and signing a txn, the View Vote panel is still open 

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#677]
The panel should automatically close after executing the vote

![image](https://user-images.githubusercontent.com/2584493/56005098-039b3600-5ccf-11e9-8d58-d9a0ecf794fb.png)

**Comment by chadoh** [comment]
@rkzel I think this may have been fixed as part of #1177. Please double-check as part of your current effort to match Dot Voting to the designs.

**Comment by rkzel** [comment]
We don't use Panels in DV anymore - but in the spirit of this ticket I made the Details tab close after vote is executed.

**Comment by stellarmagnet** [comment]
I don’t think we should automatically close page tabs!
