### ISSUE TITLE
Standardize multiline description input components

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#692]
In Projects app we use two different components for multiline description inputs (New Issue Panel, New Issue Curation Panel). 

At some point we should standardize this. 

Does Aragon's TextInput component not allow us to customize the height? 

If not, we should probably enhance that component and submit a PR to aragon-ui.

Let's do an audit of where we use this component type in our apps as well.

**Comment by javieralaves** [comment]
Closing this as we already have paragraph inputs :)
