### ISSUE TITLE
Projects filters: Ability to view issues that I have been assigned to via the funding flow

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#754]
**User story**
As a bounty hunter, I want the ability to view bounties I have applied to work on

**Comment by jayalaves** [comment]
We could add an additional filter section with three checkboxes as shown below that would give users the ability to filter for only tasks with bounties, bounties they've applied to, and bounties they've successfully been assigned to. Also helpful at tackling #612.

![Toolbar with Bounties](https://user-images.githubusercontent.com/28843778/60077494-5c089e00-972a-11e9-82d9-1949d550fb9a.jpg)

**Comment by stellarmagnet** [comment]
@jayalaves I think having it be in the toolbar makes sense, but this clashes with "status" a bit, so we need better terminology for the filter name, and to also remove the "tasks with bounties" option. does applied means issues i have applied to?

![image](https://user-images.githubusercontent.com/2584493/60341939-68059180-99b0-11e9-9d67-a9457e26f399.png)

**Comment by stellarmagnet** [comment]
Actually now that I think of it, we can maybe add the "Issues i've applied to" as another option in the status menu.

**Comment by jayalaves** [comment]
> Actually now that I think of it, this can probably be really east and we can maybe add the "Issues i've applied to" as another option in the Status menu.

That sounds like a good design fit! I think it's important to have some filters that deal with user interactions like "issues I've applied to", or "issues I've commented on", and so on. These could lead to great use cases for Home widgets. You could theoretically create some sort of handy user Kanban boards if we implemented these type of tags.

**Comment by stellarmagnet** [comment]
Closing: this should be covered in #1113
