### ISSUE TITLE
Add repo URL to links on Issue detail

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#756]
When the body of an issue comes back from GitHub with links to other GitHub issues in it, we're rendering them as plain text:

![Screen Shot 2019-07-03 at 16.46.22.png](https://images.zenhubusercontent.com/5699129a638e718c99601ac2/791ac7c0-e57e-40ff-8293-df7f83cc8442)

Let's render them as links.

**Comment by prabodhmeshram** [comment]
Hi,

I might fix this just few questions.

@stellarmagnet There is no details on the github Readme.md just after background there is The Suites, check the screenshot.
<img width="1154" alt="Screenshot 2019-04-15 at 12 51 26 PM" src="https://user-images.githubusercontent.com/6660187/56114011-310d0b80-5f7d-11e9-8aa0-9b01c25b63ab.png">

Do you mean it to be updated to The Suites and be lined ?

**Comment by stellarmagnet** [comment]
Hi @prabodhmeshram this has to do with our Projects app which lists Github issues. If there is a link inside the issue, it is not navigating to Github

**Comment by chadoh** [comment]
Looking into this, it looks like the actual markdown doesn't include any sort of indication that these issue numbers are special:

![Screen Shot 2019-07-03 at 16.55.09.png](https://images.zenhubusercontent.com/5699129a638e718c99601ac2/cd37399b-c196-41d6-8710-d23b605784b7)

To fix this issue, we'll have to parse the whole chunk of markdown that we're getting from GitHub, and match on things that look like they might be issue numbers, turning them into links back to GitHub. 

We should also think about whether there's a way to avoid false positives – things that look like issue numbers, but would not make valid links if we naïvely threw them into a URL.

**Comment by ottodevs** [comment]
This seems to be fixed:

![image](https://user-images.githubusercontent.com/5030059/70670209-b665ce80-1c78-11ea-8802-82c5caddd83c.png)

Look at the original issue 1367 to check how it references another issue, and then it is converted into a link while Projects app parses the issue text.

I will close for now. If we need to re-open this issue, please, be specific about the work that might be pending here.
