### ISSUE TITLE
Removing the re-renders in the Fund Issues panel

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#772]
1) i type in some hours, the page re-renders
2) i click on the arrow icon to expand the experience level, the page re-renders
3) i click on the calendar row to choose a deadline, it re-renders

**Comment by rkzel** [comment]
Re-renders were happening definitely at some point, and I'm slightly surprised not being able to replicate this behavior now. I added two lines of logging to 772-fund-issues-re-renders branch - they console.log when 1. Issues' render() fires and when 2. Apollo query within Issues' render() provides data. In my env neither is called, no matter what I do in FundIssue panel. Re-rendering is not happening. Please let me know what happens in your env?

**Comment by stellarmagnet** [comment]
@chadoh can I close this as I assume it will be covered in #997?

**Comment by chadoh** [comment]
@e18r @rkzel the poor performance of the side panels in Projects makes the app nearly unusable right now, so I think we should consider this part of the Projects Design System Update effort.

**Comment by stellarmagnet** [comment]
Does this problem still exist? @rkzel @chadoh

**Comment by stellarmagnet** [comment]
Just tested on mainnet on Jan 3 2020, this issue doesn't exist anymore.
