### ISSUE TITLE
List Individual Token reward amounts and their USD values

### ISSUE THREAD

**Issue by topocount** [AutarkLabs/open-enterprise#780]
Currently All token claims and awards are converted to USD and summed. On the Overview Tab and possibly the My Reward Tab, it might be better to display the individual amounts for each token, along with the converted amount in subtext.

⚠️ Depending on how this is redesigned, this may require contract changes.

**Comment by javieralaves** [comment]
Addressed by the specs in 'Enhanced Rewards' in the product repo.
