### ISSUE TITLE
Add additional permissions in Dot Voting

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#835]
Permission to modify minParticipationPct [MODIFY_QUORUM]
Permission to modify globalCandidateSupportPct [MODIFY_CANDIDATE_SUPPORT]

Ensure all appropriate corresponding getters/setters are implemented and accessible.

**Comment by Quazia** [comment]
There are potential security implications to being able to modify the quorum; I believe they've been addressed by using a global setting but it's something that should be confirmed during the internal audit. Both setters will only act on votes going forward, not votes currently in progress.
