### ISSUE TITLE
Improve the Allocations app "Options Input" component

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#841]
* Unable to remove Address Book option (when there are multiple)
* Whenever a new option is added, it should not be pre-populated with the previously selected option.

**Comment by ottodevs** [comment]
Worth mention a similar approach is taken with Multisig template on Aragon client onboarding, maybe is interesting for consistency to check if their pattern fits here:
https://rinkeby.aragon.org/#/ (Select new dao, select multisig, the process to add signer accounts is quite similar for what we are looking for)

**Comment by stellarmagnet** [comment]
If we use the new autocomplete component this issue may not exist anymore

**Comment by e18r** [comment]
@stellarmagnet We're talking about this, right?
![screenshot_2019-09-06_08-59-33_715981688](https://user-images.githubusercontent.com/16065447/64433893-f9664380-d084-11e9-9bc0-7bc8480d90e4.png)



> * Unable to remove Address Book option (when there are multiple)
> 

What's the Address Book option? Do you mean the ability to write the contact name instead of the address?

> * Whenever a new option is added, it should not be pre-populated with the previously selected option.

I can't reproduce that behavior. When I click on the "Add option" button, a new text field appears, but it's empty.

**Comment by stellarmagnet** [comment]
@e18r can you follow the test script? you have to add entries to the address book first, then the address book option will be enabled

**Comment by e18r** [comment]
@stellarmagnet OK, followed test script, found address book option. But

> * Unable to remove Address Book option (when there are multiple)

Not able to reproduce. I'm able to remove it. Testing with three contacts.

**Comment by e18r** [comment]
@stellarmagnet I just managed to reproduce. Thank you.

**Comment by stellarmagnet** [comment]
Silly me: this feature will not exist in our redesign:

* We have to remove this conditional checkbox from rendering
* The input components should be autocomplete component like on the finance app withdrawl input for the recipient
