### ISSUE TITLE
Research and spec the upgrade for the new StandardBounties contract

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#857]
[There is a new StandardBounties contract](https://github.com/Bounties-Network/StandardBounties/blob/develop/contracts/StandardBounties.sol), we need to upgrade the Projects contract to both use the new StandardBounties contract as well as ensure feature parity. This will require a plan in order to ensure compatibility with the meta-transaction changes but beyond that should be fairly simple for implementation.

We also need to make sure the contract supports both multi-token bountys, and different tokens on an issue-to-issue basis.

**Comment by topocount** [comment]
I've published the results of my research [here](https://gist.github.com/topocount/3170118ebc2ec818f0a810777cde3bdc). Our next step on this is to come to consensus on the best integration path.
