### ISSUE TITLE
Development and publishing flow improvements

### ISSUE THREAD

**Issue by ottodevs** [AutarkLabs/open-enterprise#868]
This epic groups multiple tasks looking to improve the overall workflow by taking advantage on advanced techniques and industry standards related to containerisation, CI good practices and applying our experience with the Aragon stack dev stack to leverage our deployment process and make everything simpler for us and new contributors.

Main tasks:

- Improve development environment and focus it towards e2e and solidity TDD approach
- Improve publishing process by leveraging current Aragon stack
- Improve CI process and GitHub integration and connect both previous steps into it

**Comment by javieralaves** [comment]
@ottodevs Can we remove this epic?

**Comment by ottodevs** [comment]
> @ottodevs Can we remove this epic?

Totally! It seems very old, and it was superseded by some of the recent Kevin's work.
I don't think this is relevant anymore, so I close it for now.
