### ISSUE TITLE
It should not be allowed to add the same repo multiple times to a DAO on Projects app

### ISSUE THREAD

**Issue by ottodevs** [AutarkLabs/open-enterprise#882]
That should involve some kind of guard at contract level to avoid adding already added projects/repos

**Comment by rkzel** [comment]
Quick question: is it not already the case? Or is it not working? I didn't test right now, asking because I remember it used to work some time ago:

    function addRepo(
        bytes32 _repoId
    ) external auth(ADD_REPO_ROLE) returns (uint index)
    {
        require(!isRepoAdded(_repoId), "REPO_ALREADY_ADDED");
        repos[_repoId].index = repoIndex.push(_repoId) - 1;
        emit RepoAdded(_repoId, repos[_repoId].index);
        return repoIndex.length - 1;
    }
