### ISSUE TITLE
Dot Voting showing NaN sometimes for Allocation votes

### ISSUE THREAD

**Issue by ottodevs** [AutarkLabs/open-enterprise#884]
That happens at the vote Panel:
![image](https://user-images.githubusercontent.com/5030059/57385462-c71a0780-71b2-11e9-98ea-36b46704bba7.png)

I found the issue happening for example here, this DAO is using the most recent app versions atm: https://rinkeby.aragon.org/#/flight.aragonid.eth/0xd236348af8e0e1df38c52a2a6c1a5322d7f1793e

**Comment by rkzel** [comment]
Code changed quite a bit in the new version - I can't replicate this issue now. Putting in review...
