### ISSUE TITLE
Narrow MyRewards show ready to claim prematurely

### ISSUE THREAD

**Issue by topocount** [AutarkLabs/open-enterprise#887]
While the the wide table in My Rewards show the correct statuses of the Reward, the Narrow view shows "ready to claim before the period is up.

It'd also be good to double-check that Reward don't show as "ready to claim" until the Period _and_ the delay have passed

**Comment by javieralaves** [comment]
@topocount Wow, this issue has been in Done/QA for a while now. Is this problem still observable in our latest deployment?
