### ISSUE TITLE
Issue activity updates Prematurely

### ISSUE THREAD

**Issue by topocount** [AutarkLabs/open-enterprise#893]
When reviewing a user, the acceptance and possibly rejection of a user is logged in the activity stream before the tx goes through. This should not update until an event is emitted by the contract.

This behavior occurs during review for acceptance and rejections for both:
* assignment requests
* submission reviews

the actual assignment requestions and work submissions don't post until the tx goes through, which is expected behavior

**Comment by Quazia** [comment]
Should be addressed in the projects-hot-fix branch
