### ISSUE TITLE
Ganache snapshot for Docker

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#912]
A ganache snapshot should be created with each App pre deployed into the kit and published with http provider option, so the Aragon/aragon will be directly connected to each app source code

**Comment by ottodevs** [comment]
Good starting point should be customizing aragen scripts to do this task: https://github.com/aragon/aragen

**Comment by ottodevs** [comment]
Aragen finally integrated the Open Enterprise apps, I don't think this is relevant anymore.

Closing for now, feel free to create another issue if we find another use case for a custom ganache mirror.
