### ISSUE TITLE
Integrate Funding Panel Data

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/open-enterprise#967]
- [ ] Leverage [react-api reducer](https://github.com/AutarkLabs/planning-suite/blob/dev/apps/projects/app/app-state-reducer.js) to compose funding object state - this should replace the [shaping](https://github.com/AutarkLabs/planning-suite/blob/dev/apps/projects/app/components/Content/Issues.js#L380) we do in issues.js
- [ ] un-wrap any data needed from IPFS and attach it to funding object
- [ ] Connect funding data in App.js [viewFunding](https://github.com/AutarkLabs/planning-suite/pull/954/files#diff-3fa6c42ccbaac15c982bbb6999c9097dR342) 

Data elements that need to be accessible in viewFunding that arn't currently attached to issues:

1. id - this is the ID of the funding action.
2. description - This is the string entered when starting the funding action
3. issue.data.title - The issue title on github, this should be added to all issues in the reducer or at least accessible in this context.
4. issue.data.url - The URL of the issue on github, this should be added to all issues in the reducer or at least accessible in this context.

End goal is to have the [fundingProposal](https://github.com/AutarkLabs/planning-suite/pull/954/files#diff-3fa6c42ccbaac15c982bbb6999c9097dR342) constant in view funding replaced by a lookup from the issues funding ID into a key value store that maps a funding ID into a funding object. This collection of funding objects must be composed in the reducer. We can then pull the funding object from the issue passed into the function using the issues funding ID. Issues should all have a funding ID, and funding objects should all contain all of the issues that belong to that funding action.

**Comment by chadoh** [comment]
This will be done as part of #1019
