### ISSUE TITLE
research auth with haproxy

### ISSUE THREAD

**Issue by Schwartz10** [AutarkLabs/open-enterprise#991]
Questions to answer 

- how would you add an authentication microservice to haproxy? 
- what languages could the microservice be written in?
- how hard would it be to deploy?

**Comment by rkzel** [comment]
I've answered the questions here:

https://gist.github.com/rkzel/70f3cb980feddefc54f7789cfc37ce2c

It's not a very deep technical analysis, but it provides direction and initial thoughts of how the solution should be structured. Is it ok to close the ticket, or would it make sense to do more research and start describing architecture in details?
